
#ifndef _RSC_TOOL_IMAGE_H_
#define _RSC_TOOL_IMAGE_H_

#define IM_ARROW_BUTTON1_L                                 1 
#define IM_ARROW_BUTTON1_R                                 2 
#define IM_BOX_1                                           3 
#define IM_BOX_2                                           4 
#define IM_BOX_OUTLINE                                     5 
#define IM_BUTTON1_L                                       6 
#define IM_BUTTON1_L_ARROW                                 7 
#define IM_BUTTON1_M                                       8 
#define IM_BUTTON1_R                                       9 
#define IM_BUTTON1_R_ARROW                                10 
#define IM_BUTTON2_L                                      11 
#define IM_BUTTON2_M                                      12 
#define IM_BUTTON2_R                                      13 
#define IM_BUTTON3_L                                      14 
#define IM_BUTTON3_M                                      15 
#define IM_BUTTON3_R                                      16 
#define IM_BUTTON4_L                                      17 
#define IM_BUTTON4_L_ARROW                                18 
#define IM_BUTTON4_M                                      19 
#define IM_BUTTON4_R                                      20 
#define IM_BUTTON4_R_ARROW                                21 
#define IM_BUTTON5_L                                      22 
#define IM_BUTTON5_L_ARROW                                23 
#define IM_BUTTON5_M                                      24 
#define IM_BUTTON5_R                                      25 
#define IM_BUTTON5_R_ARROW                                26 
#define IM_FRAME_LD                                       27 
#define IM_FRAME_LT                                       28 
#define IM_FRAME_MD                                       29 
#define IM_FRAME_ML                                       30 
#define IM_FRAME_MR                                       31 
#define IM_FRAME_MT                                       32 
#define IM_FRAME_RD                                       33 
#define IM_FRAME_RT                                       34 
#define IM_ICON_B_1                                       35 
#define IM_ICON_CW_1                                      36 
#define IM_BLACK                                          37 
#define IM_CHANGE                                         38 
#define IM_CHESS_SELECT_LEFTBOTTOM                        39 
#define IM_CHESS_SELECT_LEFTOP                            40 
#define IM_CHESS_SELECT_RIGHTBOTTOM                       41 
#define IM_CHESS_SELECT_RIGHTOP                           42 
#define IM_EPG_BOOK                                       43 
#define IM_EPG_COLORBUTTON_BLUE                           44 
#define IM_EPG_COLORBUTTON_GREEN                          45 
#define IM_EPG_COLORBUTTON_RED                            46 
#define IM_EPG_COLORBUTTON_YELLOW                         47 
#define IM_EPG_INFOR                                      48 
#define IM_EXIT                                           49 
#define IM_F1                                             50 
#define IM_F2                                             51 
#define IM_F3                                             52 
#define IM_F4                                             53 
#define IM_FAV                                            54 
#define IM_GAME_BOARD_MID                                 55 
#define IM_GAME_TETRIS_BLOCK_01                           56 
#define IM_GAME_TETRIS_BLOCK_02                           57 
#define IM_GAME_TETRIS_BLOCK_03                           58 
#define IM_GAME_TETRIS_BLOCK_04                           59 
#define IM_GAME_TETRIS_BLOCK_05                           60 
#define IM_GAME_TETRIS_BLOCK_06                           61 
#define IM_GAME_TETRIS_BLOCK_07                           62 
#define IM_GAME_TETRIS_BLOCK_08                           63 
#define IM_ICONS_PLAY                                     64 
#define IM_ICONS_TRICK                                    65 
#define IM_ICON_EMAIL                                     66 
#define IM_INDEX_ARROW_DOWN                               67 
#define IM_INDEX_ARROW_UP                                 68 
#define IM_INDEX_BG                                       69 
#define IM_INDEX_BG_L                                     70 
#define IM_INDEX_BG_LD                                    71 
#define IM_INDEX_BG_LT                                    72 
#define IM_INDEX_BG_M                                     73 
#define IM_INDEX_BG_MD                                    74 
#define IM_INDEX_BG_ML                                    75 
#define IM_INDEX_BG_MR                                    76 
#define IM_INDEX_BG_MT                                    77 
#define IM_INDEX_BG_R                                     78 
#define IM_INDEX_BG_RD                                    79 
#define IM_INDEX_BG_RT                                    80 
#define IM_INDEX_CA                                       81 
#define IM_INDEX_CA_FOCUS                                 82 
#define IM_INDEX_CHANNELLIST                              83 
#define IM_INDEX_CHANNELLIST_FOCUS                        84 
#define IM_INDEX_INSTALLATION                             85 
#define IM_INDEX_INSTALLATION_FOCUS                       86 
#define IM_INDEX_MEDIA_PLAYER                             87 
#define IM_INDEX_MEDIA_PLAYER_FOCUS                       88 
#define IM_INDEX_MENULINE                                 89 
#define IM_INDEX_SYSTEM                                   90 
#define IM_INDEX_SYSTEM_FOCUS                             91 
#define IM_INDEX_TOOLS                                    92 
#define IM_INDEX_TOOLS_FOCUS                              93 
#define IM_INFO                                           94 
#define IM_INFORMATION_FB_1                               95 
#define IM_INFORMATION_FB_2                               96 
#define IM_INFORMATION_FF_1                               97 
#define IM_INFORMATION_FF_2                               98 
#define IM_INFORMATION_ICON_6                             99 
#define IM_INFORMATION_ICON_6_2                          100 
#define IM_INFORMATION_ICON_7                            101 
#define IM_INFORMATION_ICON_7_2                          102 
#define IM_INFORMATION_ICON_BG_L                         103 
#define IM_INFORMATION_ICON_BG_M                         104 
#define IM_INFORMATION_ICON_BG_R                         105 
#define IM_INFORMATION_ICON_EPG                          106 
#define IM_INFORMATION_ICON_EPG_2                        107 
#define IM_INFORMATION_ICON_LEFT                         108 
#define IM_INFORMATION_ICON_MONEY                        109 
#define IM_INFORMATION_ICON_MONEY_2                      110 
#define IM_INFORMATION_ICON_MONEY_INDIA                  111 
#define IM_INFORMATION_ICON_MONEY_INDIA_2                112 
#define IM_INFORMATION_ICON_NOSIGNAL                     113 
#define IM_INFORMATION_ICON_RIGHT                        114 
#define IM_INFORMATION_ICON_SKIP                         115 
#define IM_INFORMATION_ICON_SKIP_2                       116 
#define IM_INFORMATION_ICON_STEREO                       117 
#define IM_INFORMATION_ICON_SUBTITLE                     118 
#define IM_INFORMATION_ICON_SUBTITLE_2                   119 
#define IM_INFORMATION_ICON_TTX                          120 
#define IM_INFORMATION_ICON_TTX_2                        121 
#define IM_INFORMATION_NOSIGNAL                          122 
#define IM_INFORMATION_PVR                               123 
#define IM_INFORMATION_REC                               124 
#define IM_INFORMATION_RECING                            125 
#define IM_INFORMATION_TIME                              126 
#define IM_INFORMATION_TS                                127 
#define IM_KEYBOARD_BAR_LEFT                             128 
#define IM_KEYBOARD_BAR_MIDDLE                           129 
#define IM_KEYBOARD_BAR_RIGHT                            130 
#define IM_KEYBOARD_ITEM_BLANK                           131 
#define IM_KEYBOARD_ITEM_LEFT                            132 
#define IM_KEYBOARD_ITEM_RIGHT                           133 
#define IM_KEYBOARD_ITEM_SELECT                          134 
#define IM_KEYBOARD_ITEM_SELECT_V2_LR                    135 
#define IM_KEYBOARD_ITEM_SELECT_V2_M                     136 
#define IM_KEYBOARD_ITEM_V2_LR                           137 
#define IM_KEYBOARD_ITEM_V2_M                            138 
#define IM_KEYBOARD_TAB_BG                               139 
#define IM_KEYBOARD_TAB_L                                140 
#define IM_KEYBOARD_TAB_M                                141 
#define IM_KEYBOARD_TAB_R                                142 
#define IM_MENU                                          143 
#define IM_MP3_ICON_BMP                                  144 
#define IM_MP3_ICON_FB                                   145 
#define IM_MP3_ICON_FB_SELECT                            146 
#define IM_MP3_ICON_FB_SELECT_V2                         147 
#define IM_MP3_ICON_FB_V2                                148 
#define IM_MP3_ICON_FF                                   149 
#define IM_MP3_ICON_FF_SELECT                            150 
#define IM_MP3_ICON_FF_SELECT_V2                         151 
#define IM_MP3_ICON_FF_V2                                152 
#define IM_MP3_ICON_FOLDER                               153 
#define IM_MP3_ICON_GIF                                  154 
#define IM_MP3_ICON_JPG                                  155 
#define IM_MP3_ICON_LISTPLAY                             156 
#define IM_MP3_ICON_LISTPLAY_R                           157 
#define IM_MP3_ICON_MP3                                  158 
#define IM_MP3_ICON_NO_REPEAT                            159 
#define IM_MP3_ICON_PAUSE                                160 
#define IM_MP3_ICON_PAUSE_SELECT                         161 
#define IM_MP3_ICON_PLAY_1                               162 
#define IM_MP3_ICON_PLAY_2                               163 
#define IM_MP3_ICON_PLAY_2_SELECT                        164 
#define IM_MP3_ICON_PLAY_R                               165 
#define IM_MP3_ICON_PLAY_REPEAT                          166 
#define IM_MP3_ICON_PNG                                  167 
#define IM_MP3_ICON_SB                                   168 
#define IM_MP3_ICON_SB_SELECT                            169 
#define IM_MP3_ICON_SF                                   170 
#define IM_MP3_ICON_SF_SELECT                            171 
#define IM_MP3_ICON_SINGLE_R                             172 
#define IM_MP3_ICON_STOP                                 173 
#define IM_MP3_ICON_STOP_SELECT                          174 
#define IM_MUTE                                          175 
#define IM_MUTE_S                                        176 
#define IM_M_ICON_3GP                                    177 
#define IM_M_ICON_AVI                                    178 
#define IM_M_ICON_F4V                                    179 
#define IM_M_ICON_FLV                                    180 
#define IM_M_ICON_M2TS                                   181 
#define IM_M_ICON_MKV                                    182 
#define IM_M_ICON_MOV                                    183 
#define IM_M_ICON_MP4                                    184 
#define IM_M_ICON_MPG                                    185 
#define IM_M_ICON_TS                                     186 
#define IM_NUMBER_0                                      187 
#define IM_NUMBER_1                                      188 
#define IM_NUMBER_2                                      189 
#define IM_NUMBER_3                                      190 
#define IM_NUMBER_4                                      191 
#define IM_NUMBER_5                                      192 
#define IM_NUMBER_6                                      193 
#define IM_NUMBER_7                                      194 
#define IM_NUMBER_8                                      195 
#define IM_NUMBER_9                                      196 
#define IM_OK                                            197 
#define IM_PAGE                                          198 
#define IM_PASSWORD_1                                    199 
#define IM_PASSWORD_2                                    200 
#define IM_PAUSE                                         201 
#define IM_PAUSE_S                                       202 
#define IM_RECALL                                        203 
#define IM_RENAME_PENCIL                                 204 
#define IM_SAT                                           205 
#define IM_SCROLL_BAR_BG                                 206 
#define IM_SCROLL_BAR_BG_BOTTOM                          207 
#define IM_SCROLL_BAR_BG_TOP                             208 
#define IM_SCROLL_SCROLL_BOTTOM                          209 
#define IM_SCROLL_SCROLL_MIDDLE                          210 
#define IM_SCROLL_SCROLL_TOP                             211 
#define IM_SHORTCUT                                      212 
#define IM_SIGNALBG_MIDDLE                               213 
#define IM_SIGNAL_ORANGE_MIDDLE                          214 
#define IM_SWORD_L                                       215 
#define IM_SWORD_R                                       216 
#define IM_TITLEICON_TV                                  217 
#define IM_TVRADIO                                       218 
#define IM_TVWIN01_B_SMALL                               219 
#define IM_TVWIN01_LB_SMALL                              220 
#define IM_TVWIN01_LT_SMALL                              221 
#define IM_TVWIN01_L_SMALL                               222 
#define IM_TVWIN01_RB_SMALL                              223 
#define IM_TVWIN01_RT_SMALL                              224 
#define IM_TVWIN01_R_SMALL                               225 
#define IM_TVWIN01_T_SMALL                               226 
#define IM_TV_DEL                                        227 
#define IM_TV_FAV                                        228 
#define IM_TV_FAV1                                       229 
#define IM_TV_FAV2                                       230 
#define IM_TV_FAV3                                       231 
#define IM_TV_FAV4                                       232 
#define IM_TV_FAV5                                       233 
#define IM_TV_FAV6                                       234 
#define IM_TV_FAV7                                       235 
#define IM_TV_FAV8                                       236 
#define IM_TV_HD                                         237 
#define IM_TV_LOCK                                       238 
#define IM_TV_MONEY                                      239 
#define IM_TV_MONEY_INDIA                                240 
#define IM_TV_MOVE                                       241 
#define IM_TV_SELECT                                     242 
#define IM_TV_SKIP                                       243 
#define IM_UPDOWN                                        244 
#define IM_VOL                                           245 
#define IM_VOLUMEBG_L                                    246 
#define IM_VOLUMEBG_M                                    247 
#define IM_VOLUMEBG_R                                    248 
#define IM_VOLUME_HORN                                   249 
#define IM_VOLUME_L                                      250 
#define IM_VOLUME_M                                      251 
#define IM_VOLUME_R                                      252 
#define IM_WHITE                                         253 
#define IM_ZOOM_DOWN                                     254 
#define IM_ZOOM_IN                                       255 
#define IM_ZOOM_LEFT                                     256 
#define IM_ZOOM_RIGHT                                    257 
#define IM_ZOOM_UP                                       258 
#define IM_MEDIAPLAY_70                                  259 
#define IM_MEDIAPLAY_72                                  260 
#define IM_MP3_LOGO_MUSIC_SMALL                          261 

#endif
