
#ifndef _RSC_TOOL_STRING_ID_H_
#define _RSC_TOOL_STRING_ID_H_

#define IDS_012V                                           1 
#define IDS_1318V                                          2 
#define IDS_13V                                            3 
#define IDS_18V                                            4 
#define IDS_22K                                            5 
#define IDS_A_PID                                          6 
#define IDS_ADD                                            7 
#define IDS_ADD_SAT                                        8 
#define IDS_ADD_TP                                         9 
#define IDS_ALL                                           10 
#define IDS_ANTENNA_CONNECTION                            11 
#define IDS_ANTENNA_SET                                   12 
#define IDS_ASPECT_MODE                                   13 
#define IDS_AUDIO_MODE                                    14 
#define IDS_AUDIO_MODE_LEFT                               15 
#define IDS_AUDIO_MODE_MONO                               16 
#define IDS_AUDIO_MODE_RIGHT                              17 
#define IDS_AUDIO_MODE_STEREO                             18 
#define IDS_AUDIO_SET                                     19 
#define IDS_AUDIO_TRACK                                   20 
#define IDS_AUDIO_TRACK_X                                 21 
#define IDS_AUTO                                          22 
#define IDS_BEEPER                                        23 
#define IDS_BLACK_SCREEN                                  24 
#define IDS_BLIND_SCAN                                    25 
#define IDS_BOOTLOADER                                    26 
#define IDS_CANCEL                                        27 
#define IDS_CAPS                                          28 
#define IDS_CHANGE                                        29 
#define IDS_CHANNEL_CHANGE                                30 
#define IDS_CHANNEL_LIST                                  31 
#define IDS_CHANNEL_LOCK                                  32 
#define IDS_CHANNEL_PLAY_TYPE                             33 
#define IDS_CHAR_A                                        34 
#define IDS_CHAR_B                                        35 
#define IDS_CHAR_E                                        36 
#define IDS_CHAR_N                                        37 
#define IDS_CHAR_S                                        38 
#define IDS_CHAR_W                                        39 
#define IDS_CODE_EDIT                                     40 
#define IDS_CONFIRM_PASSWORD                              41 
#define IDS_CONTINUOUS                                    42 
#define IDS_DAILY                                         43 
#define IDS_DATE                                          44 
#define IDS_DEFAULT_DB                                    45 
#define IDS_DELETE                                        46 
#define IDS_DELETE_ALL                                    47 
#define IDS_DISABLE                                       48 
#define IDS_DISEQC_10                                     49 
#define IDS_DISEQC_11                                     50 
#define IDS_DISEQC_12                                     51 
#define IDS_DISPLAY_MODE                                  52 
#define IDS_DOWNLOAD_PID                                  53 
#define IDS_DURATION_TIME                                 54 
#define IDS_EAST                                          55 
#define IDS_EDIT                                          56 
#define IDS_EDIT_SAT                                      57 
#define IDS_EDIT_TP                                       58 
#define IDS_ENABLE                                        59 
#define IDS_EPG                                           60 
#define IDS_EXIT                                          61 
#define IDS_FACTORY_SET                                   62 
#define IDS_FAILED                                        63 
#define IDS_FAV                                           64 
#define IDS_FAVORITE                                      65 
#define IDS_FIND                                          66 
#define IDS_FIRST_AUDIO                                   67 
#define IDS_FIXED_ANTENNA                                 68 
#define IDS_FREE                                          69 
#define IDS_FREEZE                                        70 
#define IDS_FREQUECY                                      71 
#define IDS_FTA_ONLY                                      72 
#define IDS_FULL_SCAN                                     73 
#define IDS_GAME                                          74 
#define IDS_GAME_BLACK                                    75 
#define IDS_GAME_CLASS                                    76 
#define IDS_GAME_EASY                                     77 
#define IDS_GAME_HARD                                     78 
#define IDS_GAME_LENGTH                                   79 
#define IDS_GAME_LEVEL                                    80 
#define IDS_GAME_LINES                                    81 
#define IDS_GAME_MSG_FOR_BLACK_FIRST                      82 
#define IDS_GAME_MSG_FOR_EXIT                             83 
#define IDS_GAME_MSG_YOU_LOSE                             84 
#define IDS_GAME_MSG_YOU_WIN                              85 
#define IDS_GAME_NORMAL                                   86 
#define IDS_GAME_OTHELLO                                  87 
#define IDS_GAME_SCORE                                    88 
#define IDS_GAME_TETRIS                                   89 
#define IDS_GAME_WHITE                                    90 
#define IDS_GMT_OFFSET                                    91 
#define IDS_GMT_USAGE                                     92 
#define IDS_HORI                                          93 
#define IDS_INFORMATION                                   94 
#define IDS_INPUT                                         95 
#define IDS_INSTALLATION                                  96 
#define IDS_LANGUAGE                                      97 
#define IDS_LANGUAGE_ARABIC                               98 
#define IDS_LANGUAGE_ENGLISH                              99 
#define IDS_LANGUAGE_FARSI                               100 
#define IDS_LANGUAGE_FRENCH                              101 
#define IDS_LANGUAGE_GERMAN                              102 
#define IDS_LANGUAGE_ITALIAN                             103 
#define IDS_LANGUAGE_POLAND                              104 
#define IDS_LANGUAGE_PORTUGUESE                          105 
#define IDS_LANGUAGE_RUSSIAN                             106 
#define IDS_LANGUAGE_SPANISH                             107 
#define IDS_LANGUAGE_TURKISH                             108 
#define IDS_LANGUAGE_TRADITIONAL_CHINESE                 109 
#define IDS_LNB_TYPE                                     110 
#define IDS_LOCAL_TIME_SET                               111 
#define IDS_LOCAL_VERSION                                112 
#define IDS_LOCK                                         113 
#define IDS_LONGITUDE                                    114 
#define IDS_MAINCODE                                     115 
#define IDS_MENU                                         116 
#define IDS_MENU_LOCK                                    117 
#define IDS_MONTHLY                                      118 
#define IDS_MOTOR_ANTENNA                                119 
#define IDS_MOTOR_SETUP                                  120 
#define IDS_MOTOR_TYPE                                   121 
#define IDS_MOVE                                         122 
#define IDS_MSG_ASK_FOR_CLEAR_SAT_POSITION               123 
#define IDS_MSG_ASK_FOR_CLEAR_TUNER_POSITION             124 
#define IDS_MSG_ASK_FOR_DEL                              125 
#define IDS_MSG_ASK_FOR_EXIT_SCAN                        126 
#define IDS_ASK_AUTOSCAN                                 127 
#define IDS_ASK_AUTOSCAN_NOPRG                           128 
#define IDS_MSG_ASK_FOR_RECALC_ALL_POSITION              129 
#define IDS_MSG_ASK_FOR_RESTORE_TO_FACTORY               130 
#define IDS_MSG_ASK_FOR_SAV                              131 
#define IDS_MSG_ASK_FOR_STANDBY                          132 
#define IDS_MSG_ASK_FOR_UPGRADE                          133 
#define IDS_MSG_CA_CARD_IN                               134 
#define IDS_MSG_CA_CARD_OUT                              135 
#define IDS_MSG_COLLECTING                               136 
#define IDS_MSG_DISABLE_LIMIT                            137 
#define IDS_MSG_EAST_LIMIT                               138 
#define IDS_MSG_ENCRYPT_PROG                             139 
#define IDS_MSG_EVENT_IS_PLAYING                         140 
#define IDS_MSG_EVT_FINISHED                             141 
#define IDS_MSG_EVT_NOTIFIED                             142 
#define IDS_MSG_FINISHED                                 143 
#define IDS_MSG_GOTO_REFERENCE                           144 
#define IDS_MSG_INPUT_PASSWORD                           145 
#define IDS_MSG_INVALID_NAME                             146 
#define IDS_MSG_INVALID_NUMBER                           147 
#define IDS_MSG_LNB_SHORT                                148 
#define IDS_MSG_MAX_CHANNEL_COUNT                        149 
#define IDS_MSG_MOVE_TO_POSITION                         150 
#define IDS_MSG_MOVING_DISH                              151 
#define IDS_MSG_N_RADIO                                  152 
#define IDS_MSG_N_TV                                     153 
#define IDS_MSG_NO_CONTENT                               154 
#define IDS_MSG_NO_FAV_PROG                              155 
#define IDS_MSG_NO_INFORMATION                           156 
#define IDS_MSG_NO_PROG                                  157 
#define IDS_MSG_NO_PROG_FOUND                            158 
#define IDS_MSG_NO_RADIO_PROG                            159 
#define IDS_MSG_NO_SIGNAL                                160 
#define IDS_MSG_NO_TELETEXT                              161 
#define IDS_MSG_NO_TV_PROG                               162 
#define IDS_MSG_OUT_OF_RANGE                             163 
#define IDS_MSG_POSITION_NOT_SPECIFIED                   164 
#define IDS_MSG_RECEIVE_END                              165 
#define IDS_MSG_REINPUT_PASSWORD                         166 
#define IDS_MSG_SAME_SAT                                 167 
#define IDS_MSG_SAME_TP                                  168 
#define IDS_MSG_SAVING                                   169 
#define IDS_MSG_SEARCH_IS_END                            170 
#define IDS_MSG_SPACE_IS_FULL                            171 
#define IDS_MSG_TIMEOUT                                  172 
#define IDS_MSG_TIMER_CONFLICT                           173 
#define IDS_MSG_WEAK_SIGNAL                              174 
#define IDS_MSG_WEST_LIMIT                               175 
#define IDS_MULTI_SAT_SEARCH                             176 
#define IDS_NAME                                         177 
#define IDS_NETWORK_SEARCH                               178 
#define IDS_NEW_PASSWORD                                 179 
#define IDS_NO                                           180 
#define IDS_NORMAL                                       181 
#define IDS_OFF                                          182 
#define IDS_OK                                           183 
#define IDS_ON                                           184 
#define IDS_ON_TIME                                      185 
#define IDS_ONCE                                         186 
#define IDS_ONE_MIN_LEFT                                 187 
#define IDS_OSD_SET                                      188 
#define IDS_OSD_TIMEOUT                                  189 
#define IDS_OSD_TRANSPARENCY                             190 
#define IDS_OTHER                                        191 
#define IDS_PAGE                                         192 
#define IDS_PARENTAL_LOCK                                193 
#define IDS_PAUSE                                        194 
#define IDS_PCR_PID                                      195 
#define IDS_PID                                          196 
#define IDS_POLARITY                                     197 
#define IDS_RADIO                                        198 
#define IDS_RADIO_CHANNEL                                199 
#define IDS_RADIO_CHANNEL_LIST                           200 
#define IDS_RADIOLOGO                                    201 
#define IDS_RENAME                                       202 
#define IDS_SAVE                                         203 
#define IDS_SCAN_CHANNEL                                 204 
#define IDS_SCAN_MODE                                    205 
#define IDS_SCRAMBLED                                    206 
#define IDS_SEARCH                                       207 
#define IDS_SECOND_AUDIO                                 208 
#define IDS_SELECT                                       209 
#define IDS_SERVICE_VERSION                              210 
#define IDS_SIGNAL_INTENSITY                             211 
#define IDS_SIGNAL_QUALITY                               212 
#define IDS_SINGLE_SAT_SEARCH                            213 
#define IDS_SKIP                                         214 
#define IDS_SLEEP_TIME                                   215 
#define IDS_SLEEP_TIMER                                  216 
#define IDS_SORT                                         217 
#define IDS_SORT_CA_FLAG                                 218 
#define IDS_SORT_DEFAULT                                 219 
#define IDS_SORT_LOCK                                    220 
#define IDS_SORT_NAME_AZ                                 221 
#define IDS_SORT_NAME_ZA                                 222 
#define IDS_STANDARD                                     223 
#define IDS_START                                        224 
#define IDS_STOP                                         225 
#define IDS_SUBTITLE_DISPLAY                             226 
#define IDS_SUBTITLE_LANGUAGE                            227 
#define IDS_SUMMER_TIME                                  228 
#define IDS_SYMBOL                                       229 
#define IDS_SYSTEM                                       230 
#define IDS_TELETEXT_LANGUAGE                            231 
#define IDS_TEST_MENU                                    232 
#define IDS_TIME                                         233 
#define IDS_TIMER_MODE                                   234 
#define IDS_TIMER_SET                                    235 
#define IDS_TOOLS                                        236 
#define IDS_TP_LIST                                      237 
#define IDS_TP_SEARCH                                    238 
#define IDS_TTX_HELP_EXIT                                239 
#define IDS_TTX_HELP_PAGE                                240 
#define IDS_TTX_HELP_TRANSPARENCE                        241 
#define IDS_TV                                           242 
#define IDS_TV_AND_RADIO                                 243 
#define IDS_TV_CHANNEL                                   244 
#define IDS_TV_CHANNEL_LIST                              245 
#define IDS_TV_SYSTEM                                    246 
#define IDS_UNIT_KSS                                     247 
#define IDS_UNIT_MHZ                                     248 
#define IDS_UNIVERSAL                                    249 
#define IDS_UPGRADE_ALL_CODE                             250 
#define IDS_UPGRADE_BY_RS232                             251 
#define IDS_UPGRADE_BY_SAT                               252 
#define IDS_UPGRADE_MODE                                 253 
#define IDS_UPGRADE_TYPE                                 254 
#define IDS_USER_DB                                      255 
#define IDS_V_PID                                        256 
#define IDS_VBI_INSERTER                                 257 
#define IDS_VERSION_INFO                                 258 
#define IDS_VERT                                         259 
#define IDS_VIDEO_OUTPUT                                 260 
#define IDS_WAKEUP_CHANNEL                               261 
#define IDS_WAKEUP_DATE                                  262 
#define IDS_WEST                                         263 
#define IDS_YEARLY                                       264 
#define IDS_YES                                          265 
#define IDS_MON                                          266 
#define IDS_TUS                                          267 
#define IDS_WED                                          268 
#define IDS_THU                                          269 
#define IDS_FRI                                          270 
#define IDS_SAT                                          271 
#define IDS_SUN                                          272 
#define IDS_WEEKLY                                       273 
#define IDS_MSG_NO_GROUP_TV                              274 
#define IDS_MSG_NO_GROUP_RADIO                           275 
#define IDS_UPGRADE_BY_USB                               276 
#define IDS_UPGRADE_FILE                                 277 
#define IDS_NO_FILE                                      278 
#define IDS_IMAGE_FILE                                   279 
#define IDS_MISC_FILES                                   280 
#define IDS_TP_PROG_DBS                                  281 
#define IDS_BACK_LOGO                                    282 
#define IDS_CCCAM_CFG                                    283 
#define IDS_CONSTANT_CW                                  284 
#define IDS_IGNORE_LIST                                  285 
#define IDS_REPLACE_LIST                                 286 
#define IDS_NEWCAMD_LIST                                 287 
#define IDS_SURE_BURN_FLASH                              288 
#define IDS_BURN_FLASH                                   289 
#define IDS_UPGRADE_NONE                                 290 
#define IDS_MISS_UPGRADE_FILE                            291 
#define IDS_BACKUP_BY_USB                                292 
#define IDS_BACKUP_MODE                                  293 
#define IDS_DUMP_DBS_IMG                                 294 
#define IDS_SYSTEM_SET_IMG                               295 
#define IDS_CCCAM_CFG_IMG                                296 
#define IDS_CONSTANT_CW_IMG                              297 
#define IDS_IGNORE_LIST_IMG                              298 
#define IDS_REPLACE_LIST_IMG                             299 
#define IDS_NEWCAMD_LIST_IMG                             300 
#define IDS_REMOVE_USB_SAFELY                            301 
#define IDS_USB_STORAGE_CONNECT                          302 
#define IDS_USB_UPG_FILE_EXIST                           303 
#define IDS_USB_UPG_RESTART                              304 
#define IDS_SAFELY_REMOVE_USB_NOW                        305 
#define IDS_USB_DISCONNECT                               306 
#define IDS_MEDIA_CENTER                                 307 
#define IDS_MUSIC_PICTURE                                308 
#define IDS_RECORD_MANAGER                               309 
#define IDS_HDD_INFO                                     310 
#define IDS_STORAGE_FORMAT                               311 
#define IDS_DVR_CONFIG                                   312 
#define IDS_PLAY_LIST                                    313 
#define IDS_ADD_PALY_LIST                                314 
#define IDS_INFO                                         315 
#define IDS_ROOT                                         316 
#define IDS_SETUP                                        317 
#define IDS_REPEAT                                       318 
#define IDS_WAIT_PLEASE                                  319 
#define IDS_PLAY_LIST_NOT_EXIST                          320 
#define IDS_ONE_SEC                                      321 
#define IDS_TWO_SEC                                      322 
#define IDS_THREE_SEC                                    323 
#define IDS_FOUR_SEC                                     324 
#define IDS_FIVE_SEC                                     325 
#define IDS_SIX_SEC                                      326 
#define IDS_SEVEN_SEC                                    327 
#define IDS_EIGHT_SEC                                    328 
#define IDS_NINE_SEC                                     329 
#define IDS_IMAGE_FIRST                                  330 
#define IDS_MUSIC_FIRST                                  331 
#define IDS_DURATION                                     332 
#define IDS_RECORD                                       333 
#define IDS_TOTAL                                        334 
#define IDS_USED                                         335 
#define IDS_TIME_SHIFT                                   336 
#define IDS_REC_FREE                                     337 
#define IDS_FILE_SYSTEM                                  338 
#define IDS_SURE_FORMAT_USB                              339 
#define IDS_FAT                                          340 
#define IDS_NTFS                                         341 
#define IDS_DVR_PATITION                                 342 
#define IDS_SURE_CHANGE_PVR_PATITION                     343 
#define IDS_CHANGEING_PATITION                           344 
#define IDS_AUTO_SELECT_PATITION1                        345 
#define IDS_5SEC                                         346 
#define IDS_10SEC                                        347 
#define IDS_30SEC                                        348 
#define IDS_1MIN                                         349 
#define IDS_5MIN                                         350 
#define IDS_10MIN                                        351 
#define IDS_30MIN                                        352 
#define IDS_NOT_AVAILABLE                                353 
#define IDS_JUMP                                         354 
#define IDS_VOLUME                                       355 
#define IDS_STORAGE_PARTITION                            356 
#define IDS_HDD_FORMAT                                   357 
#define IDS_MUSIC                                        358 
#define IDS_PVR                                          359 
#define IDS_PHOTO                                        360 
#define IDS_NUM                                          361 
#define IDS_IMG_LIST                                     362 
#define IDS_ADD_MUSIC                                    363 
#define IDS_ADD_IMAGE                                    364 
#define IDS_SHOW_LIST                                    365 
#define IDS_NETWORK_LOCAL_SETTING                        366 
#define IDS_AGE_LIMIT                                    367 
#define IDS_VIEW_ALL                                     368 
#define IDS_LOCK_ALL                                     369 
#define IDS_7                                            370 
#define IDS_12                                           371 
#define IDS_15                                           372 
#define IDS_18                                           373 
#define IDS_RANDOM_BLOCK                                 374 
#define IDS_SLIDE_FROM_TOP                               375 
#define IDS_SLIDE_FROM_BOTTOM                            376 
#define IDS_SLIDE_FROM_LEFT                              377 
#define IDS_SHUTTER_FROM_TOP                             378 
#define IDS_SHUTTER_FROM_BOTTOM                          379 
#define IDS_PLAY                                         380 
#define IDS_IMG_PLAY_LIST                                381 
#define IDS_MUSIC_PLAY_LIST                              382 
#define IDS_SHOW_IMG_SIZE                                383 
#define IDS_SLIDE_SHOW_TIME                              384 
#define IDS_SLIDE_SHOW_REPEAT                            385 
#define IDS_FULL                                         386 
#define IDS_REAL                                         387 
#define IDS_SELECT_PLAY_LIST_TYPE                        388 
#define IDS_IMAGE                                        389 
#define IDS_RESERVE                                      390 
#define IDS_GROUP                                        391 
#define IDS_CURRENT_TIME                                 392 
#define IDS_DETAIL                                       393 
#define IDS_TABLE                                        394 
#define IDS_SCHEDULE                                     395 
#define IDS_LIST                                         396 
#define IDS_QUICK_BROWSE                                 397 
#define IDS_DIGITAL_AUDIO_OUT                            398 
#define IDS_VIDEO_RESOLUTION                             399 
#define IDS_PASSWORD_CHANGE_FINISH                       400 
#define IDS_TRANSCODING                                  401 
#define IDS_DEL                                          402 
#define IDS_CHOOSE_WRONG_FILE                            403 
#define IDS_READ_FLASH                                   404 
#define IDS_WRITE_FILE                                   405 
#define IDS_BACKUP_SUCCESS                               406 
#define IDS_BACKUP_FAIL                                  407 
#define IDS_SCAN                                         408 
#define IDS_CONFIRM                                      409 
#define IDS_FTACASHD                                     410 
#define IDS_FAVOR                                        411 
#define IDS_A_Z                                          412 
#define IDS_GO_TO                                        413 
#define IDS_GROUP_MOVE                                   414 
#define IDS_MOVIES                                       415 
#define IDS_NEWS                                         416 
#define IDS_SPORTS                                       417 
#define IDS_CHILDRENS                                    418 
#define IDS_SOCIAL                                       419 
#define IDS_CULTURE                                      420 
#define IDS_EDUCATION                                    421 
#define IDS_FTA                                          422 
#define IDS_CAS                                          423 
#define IDS_HD                                           424 
#define IDS_PICTURE                                      425 
#define IDS_SET_LIMIT                                    426 
#define IDS_SET_LOCATION                                 427 
#define IDS_NONE                                         428 
#define IDS_SHARPENING                                   429 
#define IDS_ADAPTIVE                                     430 
#define IDS_SOFT                                         431 
#define IDS_VIDEO_EFFECTS                                432 
#define IDS_AV_SETTING                                   433 
#define IDS_SELECT_ALL                                   434 
#define IDS_GET_NEW_SW_VERSION                           435 
#define IDS_IF_CHANNEL                                   436 
#define IDS_CENTER_FREQ                                  437 
#define IDS_SAT_SEARCH                                   438 
#define IDS_SCAN_TYPE                                    439 
#define IDS_RECORD_FILE                                  440 
#define IDS_SAME_FILE                                    441 
#define IDS_RECORD_FINISH                                442 
#define IDS_GROUP_TYPE                                   443 
#define IDS_EXIT_RECORD                                  444 
#define IDS_PAGE_KEYBOARD                                445 
#define IDS_KEYBOARD                                     446 
#define IDS_BOOKPG_START                                 447 
#define IDS_BOOKPG_END                                   448 
#define IDS_NO_STORAGE_FOR_RECORD                        449 
#define IDS_DURATION_TENS_THAN_CURRENT                   450 
#define IDS_TIMESHIFT_FORMAT_USB                         451 
#define IDS_TIMESHIFT_SCRAMBLE_PRO                       452 
#define IDS_TIMESHIFT_RADIO_PRO                          453 
#define IDS_UPG_FAIL                                     454 
#define IDS_SHORTCUT                                     455 
#define IDS_BACK                                         456 
#define IDS_CLOSE                                        457 
#define IDS_USB_TEST                                     458 
#define IDS_TEST_PACKET_CONFIG                           459 
#define IDS_TEST_J_STATE                                 460 
#define IDS_TEST_K_STATE                                 461 
#define IDS_J_K_SEO_ACK                                  462 
#define IDS_BUS_SUSPEND                                  463 
#define IDS_BUS_RESUME                                   464 
#define IDS_BUS_RESET                                    465 
#define IDS_TESTING                                      466 
#define IDS_USB_HUB_CONNECT                              467 
#define IDS_UNSUPPORT_USB_DEVICE                         468 
#define IDS_FULL_SPEED_USB_DEVICE_CONNECT                469 
#define IDS_LOW_SPEED_USB_DEVICE_CONNECT                 470 
#define IDS_SURE_EXIT                                    471 
#define IDS_EXIT_TIMESHIFT                               472 
#define IDS_INFO_MOVE                                    473 
#define IDS_SUPERPWD_ENABLE                              474 
#define IDS_SUPERPWD_DISABLE                             475 
#define IDS_SCART_OUT                                    476 
#define IDS_BISS                                         477 
#define IDS_CRYPTOWORKS                                  478 
#define IDS_SUBTITLE_OFF                                 479 
#define IDS_PARTITION                                    480 
#define IDS_UNSUPPORTED                                  481 
#define IDS_RESUME_PLAY                                  482 
#define IDS_BISS_IMPORT                                  483 
#define IDS_CHANNEL                                      484 
#define IDS_START_TIME                                   485 
#define IDS_END_TIME                                     486 
#define IDS_MODE                                         487 
#define IDS_RECALL_PG                                    488 
#define IDS_VIEW                                         489 
#define IDS_TEXT_ENCODE                                  490 
#define IDS_USB_ERROR                                    491 
#define IDS_CA                                           492 
#define IDS_CA_SETTING                                   493 
#define IDS_KEY_EDIT                                     494 
#define IDS_MSG_ASK_FOR_IMPORT_DATA                      495 
#define IDS_SAVE_FINISH                                  496 
#define IDS_FAILED_TO_IMPORT                             497 
#define IDS_SURE_TO_RECOVERY                             498 
#define IDS_PROVID                                       499 
#define IDS_IDX                                          500 
#define IDS_KEY_DATE                                     501 
#define IDS_FREQ_DEC                                     502 
#define IDS_SERVLD_DEC                                   503 
#define IDS_RECOVER                                      504 
#define IDS_CAID                                         505 
#define IDS_UNSUPPORTED_SEEK                             506 
#define IDS_NO_VIDEO_AUDIO                               507 
#define IDS_AUTO_SEARCH                                  508 
#define IDS_MANUAL_SEARCH                                509 
#define IDS_INSTALLATION_HELP_AUTO_SCAN_FRE              510 
#define IDS_INSTALLATION_HELP_AUTO_SCAN_SYM              511 
#define IDS_INSTALLATION_HELP_AUTO_SCAN_UP_DOWN          512 
#define IDS_INSTALLATION_HELP_AUTO_SCAN_CONST            513 
#define IDS_INSTALLATION_HELP_AUTO_SCAN_STA              514 
#define IDS_INSTALLATION_HELP_MANUAL_INSTALL             515 
#define IDS_INSTALLATION_HELP_MANUAL_INSTALL_NET         516 
#define IDS_FREQUENCY_START                              517 
#define IDS_FREQUENCY_END                                518 
#define IDS_FREQUENCY_RANGE_ERROR                        519 
#define IDS_FREQUENCY                                    520 
#define IDS_CONSTELLATION                                521 
#define IDS_UNIT_FREQ                                    522 
#define IDS_UNIT_SYMB                                    523 
#define IDS_BPSK                                         524 
#define IDS_QPSK                                         525 
#define IDS_8PSK                                         526 
#define IDS_QAM16                                        527 
#define IDS_QAM32                                        528 
#define IDS_QAM64                                        529 
#define IDS_QAM128                                       530 
#define IDS_QAM256                                       531 
#define IDS_START_SEARCH                                 532 
#define IDS_CN                                           533 
#define IDS_RFLEVEL                                      534 
#define IDS_NET_SEARCH                                   535 
#define IDS_BER                                          536 
#define IDS_RANGE_SEARCH                                 537 
#define IDS_BOOK_MANAGE                                  538 
#define IDS_SWITCH_WINDOW                                539 
#define IDS_CHANGE_DATE                                  540 
#define IDS_BOOK                                         541 
#define IDS_FULL_SCREEN                                  542 
#define IDS_TV_RADIO                                     543 
#define IDS_LESS_ONE_MIN                                 544 
#define IDS_BOOK_CONFLICT                                545 
#define IDS_CONFLICT_AND_REPLACE                         546 
#define IDS_EVENT_OVERTIME                               547 
#define IDS_CUR_EVENT_IS_PLAYING                         548 
#define IDS_BOOK_IS_FULL                                 549 
#define IDS_RECIEVING_EPG                                550 
#define IDS_HOME                                         551 
#define IDS_GLOBAL_VOLUME                                552 
#define IDS_GLOBAL_TRACK                                 553 
#define IDS_FREQUENCY_SETTING                            554 
#define IDS_INSTALLATION_HELP_AUTO_SCAN_PID              555 
#define IDS_SORT_TYPE                                    556 
#define IDS_CHANNEL_EDIT                                 557 
#define IDS_PROGRAM                                      558 
#define IDS_WEEK                                         559 
#define IDS_DATE_TIME                                    560 
#define IDS_LOADER_VER                                   561 
#define IDS_CUR_STBID                                    562 
#define IDS_MANUFACTURE_ID                               563 
#define IDS_HARDWARE_VER                                 564 
#define IDS_SOFTWARE_VER                                 565 
#define IDS_DOWNLOAD_DATE                                566 
#define IDS_CHANNEL_INFORMATION                          567 
#define IDS_TYPE                                         568 
#define IDS_LCN                                          569 
#define IDS_NAME2                                        570 
#define IDS_SERVICE_ID2                                  571 
#define IDS_FREQUENCE2                                   572 
#define IDS_TS_ID                                        573 
#define IDS_QAM                                          574 
#define IDS_PCR_PID2                                     575 
#define IDS_TEL_PID                                      576 
#define IDS_SYMBOL2                                      577 
#define IDS_VIDEO_PID                                    578 
#define IDS_AUDIO_PID                                    579 
#define IDS_RECEIVING_DATA                               580 
#define IDS_PROGRESS                                     581 
#define IDS_PROGRAM_NAME_NVOD                            582 
#define IDS_START_TIME_NVOD                              583 
#define IDS_END_TIME_NVOD                                584 
#define IDS_NVOD_PLAY_PROGRESS                           585 
#define IDS_NVOD_NVOD                                    586 
#define IDS_EXIT_NVOD                                    587 
#define IDS_NVOD_IS_PLAYING                              588 
#define IDS_NVOD_NOT_PLAYING                             589 
#define IDS_CATEGORY                                     590 
#define IDS_NIT_UPDATE                                   591 
#define IDS_PLEASE_CONNECT_USB                           592 
#define IDS_NO_PROG                                      593 
#define IDS_CA2                                          594 
#define IDS_MEDIA                                        595 
#define IDS_EDIT_FAV_CHANNEL                             596 
#define IDS_EXCHANGE                                     597 
#define IDS_FAV_GROUP                                    598 
#define IDS_FAV_LIST                                     599 
#define IDS_EDIT_FAVORITE_HELP                           600 
#define IDS_CA_SMARTCARD_INFO                            601 
#define IDS_CA_LEVEL_CONTROL_SET                         602 
#define IDS_CA_WOR_DURATION_SET                          603 
#define IDS_CA_ACCREDIT_PRODUCK_INFO                     604 
#define IDS_CA_PWD_MODIFY                                605 
#define IDS_CA_SLOT_INFO                                 606 
#define IDS_CA_SP_INFO                                   607 
#define IDS_CA_EMAIL                                     608 
#define IDS_CA_SP_OPERATOR_INFO                          609 
#define IDS_CA_SMART_CARD_NUMBER                         610 
#define IDS_CA_ADDRES_INFO                               611 
#define IDS_CA_CARD_STATE                                612 
#define IDS_CA_CARD_VER                                  613 
#define IDS_CA_WATCH_LEVEL                               614 
#define IDS_CA_WORK_TIME                                 615 
#define IDS_CA_MASTER_CARD_ID                            616 
#define IDS_CA_LOCAL_DIVISION_ID                         617 
#define IDS_CA_GROUP_ID                                  618 
#define IDS_CA_CARD_VERSION                              619 
#define IDS_CA_DELETE_CARD                               620 
#define IDS_CA_NO_ENABLE                                 621 
#define IDS_CA_SMC_OVERDUE                               622 
#define IDS_CA_INVALID_CARD                              623 
#define IDS_CA_CARD_STOP                                 624 
#define IDS_CA_NO_NEED_PAIR                              625 
#define IDS_CA_STB_PAIR                                  626 
#define IDS_CA_STB_PAIR_OTHER                            627 
#define IDS_CA_INPUT_PIN                                 628 
#define IDS_CA_SELECT_LEVEL                              629 
#define IDS_CA_SET_SUCCESS                               630 
#define IDS_CA_PARAME_SET_ERROR                          631 
#define IDS_CA_IC_CMD_FAIL                               632 
#define IDS_CA_PIN_NUMB_ERROR_MAX                        633 
#define IDS_CA_PASSWORD_ERROR                            634 
#define IDS_CA_PIN_CHANCES_LEFT                          635 
#define IDS_CA_PIN_INVALID                               636 
#define IDS_CA_LEVEL1                                    637 
#define IDS_CA_LEVEL2                                    638 
#define IDS_CA_LEVEL3                                    639 
#define IDS_CA_LEVEL4                                    640 
#define IDS_CA_LEVEL5                                    641 
#define IDS_CA_LEVEL6                                    642 
#define IDS_CA_LEVEL7                                    643 
#define IDS_CA_LEVEL8                                    644 
#define IDS_CA_LEVEL9                                    645 
#define IDS_CA_LEVEL10                                   646 
#define IDS_CA_LEVEL11                                   647 
#define IDS_CA_LEVEL12                                   648 
#define IDS_CA_LEVEL13                                   649 
#define IDS_CA_LEVEL14                                   650 
#define IDS_CA_LEVEL15                                   651 
#define IDS_CA_LEVEL16                                   652 
#define IDS_CA_LEVEL17                                   653 
#define IDS_CA_LEVEL18                                   654 
#define IDS_CA_START_TIME                                655 
#define IDS_CA_END_TIME                                  656 
#define IDS_CA_INPUT_OLD_PIN                             657 
#define IDS_CA_INPUT_NEW_PIN                             658 
#define IDS_CA_CONFIRM_NEW_PIN                           659 
#define IDS_CA_PRODUCT_ID                                660 
#define IDS_CA_AUTHORIZE_DEADLINE                        661 
#define IDS_CA_PURSE_BALANCE1                            662 
#define IDS_CA_PURSE_BALANCE2                            663 
#define IDS_CA_PURSE_BALANCE3                            664 
#define IDS_CA_PURSE_BALANCE4                            665 
#define IDS_CA_SP_ID                                     666 
#define IDS_CA_SP_NAME                                   667 
#define IDS_CA_OPERATOR_TEL                              668 
#define IDS_CA_OPERATOR_ADDRES                           669 
#define IDS_CA_NUMBER                                    670 
#define IDS_CA_TITLE                                     671 
#define IDS_CA_NEW_NOT                                   672 
#define IDS_LANGUAGE_SIMPLIFIED_CHINESE                  673 
#define IDS_PAL                                          674 
#define IDS_NTSC                                         675 
#define IDS_576I                                         676 
#define IDS_576P                                         677 
#define IDS_720P                                         678 
#define IDS_1080I                                        679 
#define IDS_1080P                                        680 
#define IDS_480I                                         681 
#define IDS_480P                                         682 
#define IDS_43LETTERBOX                                  683 
#define IDS_43PANSCAN                                    684 
#define IDS_169                                          685 
#define IDS_LPCM_OUT                                     686 
#define IDS_BS_OUT                                       687 
#define IDS_CVBS                                         688 
#define IDS_RGB                                          689 
#define IDS_CA_CARD_REGU_INSERT                          690 
#define IDS_CA_UNKNOW_SMC                                691 
#define IDS_CA_CARD_OVER_DATE                            692 
#define IDS_CA_CARD_INIT_FAIL                            693 
#define IDS_CA_NO_SP_IN_SMC                              694 
#define IDS_CA_CARD_OUT_WORK_TIME                        695 
#define IDS_CA_PROG_HIGH_WATCH_LEVEL                     696 
#define IDS_CA_STB_SN_NOT_MATCH                          697 
#define IDS_CA_NO_PURCH_PROG                             698 
#define IDS_CA_DECRYPTION_FAIL                           699 
#define IDS_CA_NO_MONEY                                  700 
#define IDS_CA_AREA_ERROR                                701 
#define IDS_CA_MASTERSLAVE_PAIRED_OK                     702 
#define IDS_CA_CARD_PARTNER_FAILED                       703 
#define IDS_CA_SLAVE_NEED_MASTER                         704 
#define IDS_CA_CARD_PARTNER_SUCCESS                      705 
#define IDS_CA_REPAIR_STB                                706 
#define IDS_CA_CARD_REMATCH_CANCEL                       707 
#define IDS_CA_EMAIL_NO_SPACE                            708 
#define IDS_CA_SMART_UNLOCK                              709 
#define IDS_CA_WALLET_RENEW                              710 
#define IDS_CA_CARD_NO_MONEY                             711 
#define IDS_CA_CARD_IPPV_OUT_TIME                        712 
#define IDS_CA_CARD_INIT                                 713 
#define IDS_CA_CARD_NEED_UPDATE                          714 
#define IDS_CA_CARD_NOT_INSERT                           715 
#define IDS_CA_CARD_ENTITLE_UPDATE                       716 
#define IDS_CA_CARD_CONDITIONAL_LIMIT                    717 
#define IDS_CA_CARD_NET_ERR_LOCK                         718 
#define IDS_CA_CARD_SYS_ERR_LOCK                         719 
#define IDS_CA_CARD_NET_ERR_UNLOCK                       720 
#define IDS_CA_CARD_SYS_ERR_UNLOCK                       721 
#define IDS_CA_E_CARD_ENTITLE_EXPIRED                    722 
#define IDS_CA_CARD_ADDR_CTL_OPEN                        723 
#define IDS_CA_CARD_ADDR_CTL_CLOSE                       724 
#define IDS_CA_CARD_WRITEPURSER_ERROR                    725 
#define IDS_CA_CARD_IPPV_NO_MONEY                        726 
#define IDS_CA_PATCH_TIME                                727 
#define IDS_CA_PATCH_STATUS                              728 
#define IDS_CA_INFO                                      729 
#define IDS_CA_ID                                        730 
#define IDS_CA_OPERATOR                                  731 
#define IDS_CA_ACCREDIT_INFO                             732 
#define IDS_CA_SLOT                                      733 
#define IDS_CA_IPPV                                      734 
#define IDS_CA_EIGENVALUE                                735 
#define IDS_CA_RECORDED                                  736 
#define IDS_CA_SLOT_ID                                   737 
#define IDS_CA_SLOT_POINT                                738 
#define IDS_CA_CREDIT                                    739 
#define IDS_CA_PROGRAM_ID                                740 
#define IDS_CA_STATE                                     741 
#define IDS_CA_PRICE                                     742 
#define IDS_CA_AREA_CODE                                 743 
#define IDS_CA_BUOUQUET_ID                               744 
#define IDS_CA_EIGENVALUE_INFO                           745 
#define IDS_CA_TOTAL_IPP                                 746 
#define IDS_CA_CARD_TYPE                                 747 
#define IDS_CA_PARENT_CARD_ID                            748 
#define IDS_CA_FEED_DURATION                             749 
#define IDS_CA_LAST_FEED_TIME                            750 
#define IDS_CA_CARD_MANAGE                               751 
#define IDS_CA_FEED_SUCCESS                              752 
#define IDS_CA_FEED_TIME_NOT_ARRIVE                      753 
#define IDS_CA_FEED_FAILED                               754 
#define IDS_CA_FEED_INSERT_CHILD_CARD                    755 
#define IDS_CA_MOTHER_CARD_ERR                           756 
#define IDS_CA_INSERT_PARENT_CARD                        757 
#define IDS_CA_PAIR_STATE                                758 
#define IDS_CA_PLAT_ID                                   759 
#define IDS_CA_STB_PAIR2                                 760 
#define IDS_CA_EMAIL_CONTENT                             761 
#define IDS_CA_EMAIL_RECEIVE_TIME                        762 
#define IDS_CA_IMPORT                                    763 
#define IDS_CA_UNIDENTIFIED_CARD                         764 
#define IDS_CA_BLACKOUT                                  765 
#define IDS_CA_CARD_UPGRADING                            766 
#define IDS_CA_CARD_NEED_UPG                             767 
#define IDS_CA_VIEWLOCK                                  768 
#define IDS_CA_CARD_PAUSE                                769 
#define IDS_CA_CARD_TESTSTART                            770 
#define IDS_CA_CARD_STBLOCKED                            771 
#define IDS_CA_IPPV_BUY                                  772 
#define IDS_CA_IPPV_PROGRAM_NAME                         773 
#define IDS_CA_IPPV_PRICE                                774 
#define IDS_CA_IPPV_START_TIME                           775 
#define IDS_CA_IPPV_END_TIME                             776 
#define IDS_CA_PURSE_1                                   777 
#define IDS_CA_PURSE_2                                   778 
#define IDS_CA_PURSE_3                                   779 
#define IDS_CA_PURSE_4                                   780 
#define IDS_CA_SENIOR_PREVIEW_INFO                       781 
#define IDS_CA_SLOT_ID_2                                 782 
#define IDS_CA_PROGRAM_ID_2                              783 
#define IDS_CA_AUTHORIZE_DEADLINE_2                      784 
#define IDS_CA_INPUT_PIN_2                               785 
#define IDS_CA_BILLING_INTERVAL                          786 
#define IDS_CA_PRICE_UNIT                                787 
#define IDS_CA_IPP_BUY_NO_TAPING                         788 
#define IDS_CA_IPP_BUY_TAPING                            789 
#define IDS_CA_IPP_HELP                                  790 
#define IDS_CA_DEL_CURRENT_MAIL                          791 
#define IDS_CA_DEL_ALL_MAIL                              792 
#define IDS_CA_CARD_EMAIL_ERR                            793 
#define IDS_CA_RECEIVED_DATA_FAIL                        794 
#define IDS_CA_CARD_UPGRADE_PROGRESS                     795 
#define IDS_CA_CARD_UPDATE_PROG                          796 
#define IDS_CA_WORK_TIME_ERROR                           797 
#define IDS_CA_CARD_UPDATE                               798 
#define IDS_CA_CARD_UPDATE_ERR                           799 
#define IDS_CA_SYS_ID_ERR                                800 
#define IDS_AGE_6                                        801 
#define IDS_AGE_7                                        802 
#define IDS_AGE_8                                        803 
#define IDS_AGE_9                                        804 
#define IDS_AGE_10                                       805 
#define IDS_AGE_11                                       806 
#define IDS_AGE_12                                       807 
#define IDS_AGE_13                                       808 
#define IDS_AGE_14                                       809 
#define IDS_AGE_15                                       810 
#define IDS_AGE_16                                       811 
#define IDS_AGE_17                                       812 
#define IDS_AGE_18                                       813 
#define IDS_AGE_19                                       814 
#define IDS_AGE_20                                       815 
#define IDS_AGE_21                                       816 
#define IDS_AGE_ALL                                      817 
#define IDS_CA_SMART_CARD_NAME                           818 
#define IDS_SC_STB_MATCH                                 819 
#define IDS_CA_AREA_CODE2                                820 
#define IDS_CA_CARD_INVALID                              821 
#define IDS_CA_CARD_PIN_INVALID                          822 
#define IDS_CA_CARD_UPG_FAILED                           823 
#define IDS_CA_CARD_BECOME_DUE                           824 
#define IDS_CA_CARD_RST_FAIL                             825 
#define IDS_CA_CADR_NO_MONEY                             826 
#define IDS_CA_SERVICE_LOCKED                            827 
#define IDS_CA_CADR_NOT_ACT                              828 
#define IDS_CA_ZONE_CODE_ERR                             829 
#define IDS_CA_NOT_RECEIVED_SPID                         830 
#define IDS_CA_ERROR_CARD_NOTSUPPORT                     831 
#define IDS_CA_IPP_INFO_ERROR                            832 
#define IDS_CA_FEED_DATA_ERROR                           833 
#define IDS_CA_CARD_RST_SUCCESS                          834 
#define IDS_CA_CARD_REMOVE                               835 
#define IDS_CA_MODIFY_ZONECODE                           836 
#define IDS_CA_SEVICE_NOT_SCRAMBLED                      837 
#define IDS_CA_CARD_MODULE_REMOVE                        838 
#define IDS_CA_CARD_MODULE_EEPROM_FAILED                 839 
#define IDS_CA_ILLEGAL_CARD                              840 
#define IDS_CA_CARD_CHECKING                             841 
#define IDS_CA_CARD_EEPROM_FAILED                        842 
#define IDS_CA_PMT_FORMAT_WRONG                          843 
#define IDS_CA_CARD_DIS_PARTNER                          844 
#define IDS_CA_SON_CARD_NEED_FEED                        845 
#define IDS_CA_SEVICE_NOT_AVAILABLE                      846 
#define IDS_CA_PROG_UNAUTH                               847 
#define IDS_CA_PROG_AUTH_CHANGE                          848 
#define IDS_CA_SEVICE_SCRAMBLED                          849 
#define IDS_E18                                          850 
#define IDS_E19                                          851 
#define IDS_CA_NOT_ALLOWED_BROADCASTER                   852 
#define IDS_E21                                          853 
#define IDS_E22                                          854 
#define IDS_CA_SERVICE_DISCRAMBLING                      855 
#define IDS_CA_NOT_ALLOWED_REGION                        856 
#define IDS_CA_NEED_SMC_STB_PAIR                         857 
#define IDS_CA_SEVICE_UNKNOWN                            858 
#define IDS_CA_SEVICE_NOT_RUNNING                        859 
#define IDS_CA_CARD_LOCKED                               860 
#define IDS_E29                                          861 
#define IDS_E30                                          862 
#define IDS_CA_NOT_ALLOWED_COUNTRY                       863 
#define IDS_CA_NO_AUTH_DATA                              864 
#define IDS_CA_NO_AUTH_STB                               865 
#define IDS_CA_NO_SIGNAL                                 866 
#define IDS_CA_ADPT_ILLEGAL_CARD                         867 
#define IDS_CA_AUTHEN_EXPIRED                            868 
#define IDS_CA_AUTH_EXPIRE_TIME                          869 
#define IDS_DAYS                                         870 
#define IDS_ABV_PWD_ERROR_ONE                            871 
#define IDS_ABV_PWD_ERROR_TWO                            872 
#define IDS_ABV_PWD_ERROR_THREE                          873 
#define IDS_ABV_PWD_ERROR_FOUR                           874 
#define IDS_ABV_PWD_ERROR_FIVE                           875 
#define IDS_ABV_PWD_ERROR_SIX                            876 
#define IDS_ABV_PWD_ERROR_SEVEN                          877 
#define IDS_ABV_PWD_ERROR_NONE                           878 
#define IDS_ABV_PWD_ERROR                                879 
#define IDS_SENDER                                       880 
#define IDS_RECEIVED                                     881 
#define IDS_REST_SPACE                                   882 
#define IDS_PROVIDER_INFORMATION                         883 
#define IDS_FREE_ENTITLE_INFO                            884 
#define IDS_PPC_ENTITLE_INFO                             885 
#define IDS_PPV_ENTITLE_INFO                             886 
#define IDS_CONSUME_HISTORY                              887 
#define IDS_PPID                                         888 
#define IDS_PROVIDER                                     889 
#define IDS_BALANCE                                      890 
#define IDS_LABLE                                        891 
#define IDS_START_TIME4                                  892 
#define IDS_END_TIME4                                    893 
#define IDS_LINK_ID                                      894 
#define IDS_ENTITLE_TIME                                 895 
#define IDS_MONEY                                        896 
#define IDS_SEARCH_FINISHED                              897 
#define IDS_IPP_TYPE                                     898 
#define IDS_IPP_PRICE                                    899 
#define IDS_IPP_DISTANCE                                 900 
#define IDS_IPP_INFOR2                                   901 
#define IDS_IPP_HELP                                     902 
#define IDS_CHANNEL_SWITCH_MODE                          903 
#define IDS_FREEZE_VIDEO                                 904 
#define IDS_APP_ALL                                      905 
#define IDS_SOFTWARE_UPGRADE                             906 
#define IDS_UPDATE_SOFTWARE                              907 
#define IDS_OTA_TIMEOUT                                  908 
#define IDS_USB_LOCAL_VERSION                            909 
#define IDS_USB_BIN_VERSION                              910 
#define IDS_CA_E_CARD_TARIIFF_EXPIRED                    911 
#define IDS_ADS_VERSION                                  912 
#define IDS_TS_RECORD                                    913 
#define IDS_START_RECORD                                 914 
#define IDS_CA_CARD_BALAN                                915 
#define IDS_CA_OVER_BALAN                                916 
#define IDS_CA_CONDTION_CODE                             917 
#define IDS_CA_MANUFACTURE                               918 
#define IDS_CA_SERIAL_NUMBER                             919 
#define IDS_CA_CONTR_CODE                                920 
#define IDS_CA_CARD_PAIRED                               921 
#define IDS_CA_CARD_NOT_PAIRED                           922 
#define IDS_CA_MOHTER_CARD_NUMBER                        923 
#define IDS_CA_WATCH_TIME                                924 
#define IDS_CA_REMAIN_TIME                               925 
#define IDS_CA_E_APP_RESUME                              926 
#define IDS_CA_E_PROG_UNAUTH                             927 
#define IDS_CA_E_PROG_AUTH                               928 
#define IDS_CA_E_UPDATE_GNO                              929 
#define IDS_CA_E_UPDATE_GK                               930 
#define IDS_CA_E_CHARGE                                  931 
#define IDS_CA_E_UPDATE_ZONECODE                         932 
#define IDS_CA_E_UPDATE_COUT                             933 
#define IDS_CA_E_UPDATE_CRT                              934 
#define IDS_CA_E_SCARD_NOT_ACT                           935 
#define IDS_CA_E_SCARD_DISABLED                          936 
#define IDS_CA_E_NO_MONEY                                937 
#define IDS_NO_AUTHORIZED                                938 
#define IDS_CA_E_CARD_LOCKED                             939 
#define IDS_CA_E_APP_LOCKED                              940 
#define IDS_CA_E_PIN_AUTHEN                              941 
#define IDS_CA_E_EXTER_AUTHEN                            942 
#define IDS_CA_E_CARD_NOTMATCH                           943 
#define IDS_CA_E_UPDATE_GR                               944 
#define IDS_CA_E_EN_PAPTNER                              945 
#define IDS_CA_E_DIS_PARTNER                             946 
#define IDS_CA_SET_CARD                                  947 
#define IDS_CA_SMART_CARD_PAIRD                          948 
#define IDS_CA_SMAR_CARD_UNPAIRD                         949 
#define IDS_CA_INSERT_TIME                               950 
#define IDS_CA_TIME_LOCK                                 951 
#define IDS_CA_PPV_PROG                                  952 
#define IDS_CARD_MANAGE                                  953 
#define IDS_CARD_TYPE                                    954 
#define IDS_CA_PROVIDER                                  955 
#define IDS_CA_STB_PAIR_STATUS                           956 
#define IDS_CA_CARD_LIMIT_CODE                           957 
#define IDS_CA_WALLET_TOTAL                              958 
#define IDS_CA_USER_USED                                 959 
#define IDS_CA_ENTITLE_EXPIRED                           960 
#define IDS_CA_CARD_ACTIVE_TIME                          961 
#define IDS_MOTHER_CARD_NUM                              962 
#define IDS_CA_MOTHER_CARD                               963 
#define IDS_CA_CHILD_CARD                                964 
#define IDS_PRE_AUTH                                     965 
#define IDS_CA_RENEW                                     966 
#define IDS_PROGRAM_OVERDUE_RENEW                        967 
#define IDS_CA_POINT                                     968 
#define IDS_CA_PPV_PRICE                                 969 
#define IDS_HAS_ORRDERED                                 970 
#define IDS_NOT_ORDER                                    971 
#define IDS_CA_SELECTED_STATUS_1                         972 
#define IDS_CA_PROGRAM_PRICE                             973 
#define IDS_CA_CARD_BALANCE                              974 
#define IDS_IPPV_RESCING                                 975 
#define IDS_IPPV_PROG                                    976 
#define IDS_CA_AUTH_EXPIRE_LEFT                          977 
#define IDS_IPPV_ORDER                                   978 
#define IDS_SUBSCRIPTION                                 979 
#define IDS_PAY_PER_VIEW                                 980 
#define IDS_ABOUT_CA                                     981 
#define IDS_CRYPTOGUARD_CA                               982 
#define IDS_CA_SERVICE_EMERGENCE                         983 
#define IDS_CA_AUTH_EXPIRED                              984 
#define IDS_CA_AUTH_CLOSED                               985 
#define IDS_CA_STATUS_RENEW                              986 
#define IDS_CA_AUTH_UPDATE                               987 
#define IDS_GENERAL_PRO                                  988 
#define IDS_IPP_PRO_INFO                                 989 
#define IDS_SLOT_INFO                                    990 
#define IDS_IPP_CONSUME                                  991 
#define IDS_COMMISION_STATE                              992 
#define IDS_COMMISION_DATE                               993 
#define IDS_IPP_ID                                       994 
#define IDS_REMAIN_NUMBER                                995 
#define IDS_GLIDE_NUM                                    996 
#define IDS_CA_SLAVE_NEED_PAIR                           997 
#define IDS_CA_INSERT_CHILD_CARD                         998 
#define IDS_CA_INVALID_PARENT_CARD                       999 
#define IDS_CAS_E_UNKNOWN_ERROR                         1000 
#define IDS_CA_NOT_PAIRED                               1001 
#define IDS_CA_CARD_SLEEP                               1002 
#define IDS_CA_CARD_FROZEN                              1003 
#define IDS_CA_CARD_UPG_TEST                            1004 
#define IDS_CA_CARD_UPG_TEST_FAIL                       1005 
#define IDS_CA_CARD_UPG_TEST_SUCCESS                    1006 
#define IDS_CA_CARD_CUSTOM_OPER                         1007 
#define IDS_CA_STB_FROZEN                               1008 
#define IDS_CA_WATCH_LIMIT                              1009 
#define IDS_MSG_ERR_NETWORK                             1010 
#define IDS_CA_TEST_SHOW                                1011 
#define IDS_CA_E00                                      1012 
#define IDS_CA_E01                                      1013 
#define IDS_CA_E02                                      1014 
#define IDS_CA_E03                                      1015 
#define IDS_CA_E04                                      1016 
#define IDS_CA_E05                                      1017 
#define IDS_CA_E06                                      1018 
#define IDS_CA_E07                                      1019 
#define IDS_CA_E08                                      1020 
#define IDS_CA_E09                                      1021 
#define IDS_CA_E10                                      1022 
#define IDS_CA_E11                                      1023 
#define IDS_CA_E12                                      1024 
#define IDS_CA_E13                                      1025 
#define IDS_CA_E14                                      1026 
#define IDS_CA_E15                                      1027 
#define IDS_CA_E16                                      1028 
#define IDS_CA_E17                                      1029 
#define IDS_CA_E18                                      1030 
#define IDS_CA_E19                                      1031 
#define IDS_CA_E20                                      1032 
#define IDS_CA_E21                                      1033 
#define IDS_CA_E22                                      1034 
#define IDS_CA_E23                                      1035 
#define IDS_CA_E24                                      1036 
#define IDS_CA_E25                                      1037 
#define IDS_CA_E26                                      1038 
#define IDS_CA_E27                                      1039 
#define IDS_CA_E28                                      1040 
#define IDS_CA_E29                                      1041 
#define IDS_CA_E30                                      1042 
#define IDS_CA_E31                                      1043 
#define IDS_CA_E32                                      1044 
#define IDS_CA_E33                                      1045 
#define IDS_CA_E34                                      1046 
#define IDS_CA_E35                                      1047 
#define IDS_CA_E42                                      1048 
#define IDS_FEED_PARAM_ERROR                            1049 
#define IDS_NOT_SUPPORT_FEED                            1050 
#define IDS_FEED_PARTNER_FAILED                         1051 
#define IDS_PROMPT                                      1052 
#define IDS_CURRENT_IS_MOTHER_CARD                      1053 
#define IDS_CURRENT_IS_SON_CARD                         1054 
#define IDS_CA_FEED_NULL                                1055 
#define IDS_ALERT_MESSAGE                               1056 
#define IDS_CA_ALERT                                    1057 
#define IDS_RECEIVE_TIME                                1058 
#define IDS_NEW                                         1059 
#define IDS_IMPORT                                      1060 
#define IDS_CA_AUTH_PROG_CHECK                          1061 
#define IDS_CA_PROG_INFO_CHECK                          1062 
#define IDS_CA_O_S_IPP_PROG                             1063 
#define IDS_CA_WATCHED_IPP_PROG                         1064 
#define IDS_CA_AUTH_TIME                                1065 
#define IDS_CA_CARD_COS_VER                             1066 
#define IDS_CA_STB_MODULE_VER                           1067 
#define IDS_CA_ZONE_CODE_STATUS                         1068 
#define IDS_CA_RECEIVED_ZONE_TIME                       1069 
#define IDS_CA_PIN_STATUS                               1070 
#define IDS_CA_CARD_LOCK                                1071 
#define IDS_CA_TOTAL_ENTITLED_NUB                       1072 
#define IDS_CA_CUR_PAGE                                 1073 
#define IDS_CA_MAIL_COUNT                               1074 
#define IDS_CA_UNREAD_MAIL_CNT                          1075 
#define IDS_CA_SHOW_MAX_MAIL_CNT                        1076 
#define IDS_CA_LOCKED                                   1077 
#define IDS_CA_UNLOCKED                                 1078 
#define IDS_CA_DUR_TIME                                 1079 
#define IDS_CA_CUR_PRICE                                1080 
#define IDS_CA_CUR_CHANNEL_NAME                         1081 
#define IDS_CA_ORDER_PRICE                              1082 
#define IDS_CA_IPP_TOTAL                                1083 
#define IDS_CA_IPP_SELECT                               1084 
#define IDS_CA_SELECTED_STATUS                          1085 
#define IDS_CA_PROGRAM_TYPE                             1086 
#define IDS_CA_CPC_ORDER_TIP                            1087 
#define IDS_CA_CYCLE_NUM_TO_WATCH                       1088 
#define IDS_CA_HOUR                                     1089 
#define IDS_CA_MINUTE                                   1090 
#define IDS_CA_SECOND                                   1091 
#define IDS_CA_MONTH                                    1092 
#define IDS_CA_YEARS                                    1093 
#define IDS_CA_NN_PRICE                                 1094 
#define IDS_CA_CANNOT_CHOSE_P_PG                        1095 
#define IDS_CA_SURE_TO_UNBOOK_PG                        1096 
#define IDS_CA_SURE_TO_BUY_PG                           1097 
#define IDS_CA_INVALID_PRICE                            1098 
#define IDS_CA_ORDER_SUCCESS                            1099 
#define IDS_CA_SUC_P_RACHARGE                           1100 
#define IDS_CA_NEED_VERIFY_PIN                          1101 
#define IDS_CA_US_FAIL_TO_RETRY                         1102 
#define IDS_CA_INPUT_CYC_IS_INVALID                     1103 
#define IDS_CA_CHECK_USER_PIN                           1104 
#define IDS_CA_DIGIT_NOT_ENOUGH                         1105 
#define IDS_CA_UNSU_SUCCESS                             1106 
#define IDS_CA_OTHER_INFO                               1107 
#define IDS_CA_OPEN_CLOSE_CA_DEBUG                      1108 
#define IDS_CA_MAIN_FREQ_SET                            1109 
#define IDS_CA_SIGNAL_FREQ_SET                          1110 
#define IDS_CA_OPENING_CA_LIB                           1111 
#define IDS_CA_CLOSING_CA_LIB                           1112 
#define IDS_CA_NO_IPP_UPPER_MENU                        1113 
#define IDS_CA_IS_EMERGENCY_BDCAST                      1114 
#define IDS_CA_FREE_PREVIEW                             1115 
#define IDS_CA_REAL_TIME_BUY_IPP                        1116 
#define IDS_CA_PRICE_TYPE                               1117 
#define IDS_CA_O_U_IPP                                  1118 
#define IDS_CA_PROGRAM_TYPE2                            1119 
#define IDS_CA_INSERT_MOTHER_CARD                       1120 
#define IDS_CA_MATCH_CARD_BEGIN                         1121 
#define IDS_CA_MOTHER_GET_DATA                          1122 
#define IDS_CA_MATCH_WARN                               1123 
#define IDS_CA_MATCH_SUC_OTHER_CHID_CARD                1124 
#define IDS_CA_MATCH_FAIL_INCHILD                       1125 
#define IDS_CA_EXIT_FEED_TIP                            1126 
#define IDS_CA_IC_SERVICE_BAN                           1127 
#define IDS_CA_MOTHER_CARD_NUM                          1128 
#define IDS_CA_CARD_EMAIL_DEL_ERR                       1129 
#define IDS_CA_LIMIT_WATCH_PROG                         1130 
#define IDS_CA_RMB                                      1131 
#define IDS_CA_LIMIT_AREA_WATCH                         1132 
#define IDS_CA_IPPV_NO_BOOK                             1133 
#define IDS_CA_IPPV_NO_CONFIRM                          1134 
#define IDS_CA_IPPT_NO_BOOK                             1135 
#define IDS_CA_IPPT_NO_CONFIRM                          1136 
#define IDS_CA_PROGRAM_NAME                             1137 
#define IDS_CA_PROG_SP                                  1138 
#define IDS_CA_SYS_PROVIDER                             1139 
#define IDS_CA_IMPORTANT_MAIL                           1140 
#define IDS_CA_INPUT_PASSWORD                           1141 
#define IDS_CA_PROGRAM_OVERDUE                          1142 
#define IDS_CA_WALLET_DONOT_EXIST                       1143 
#define IDS_CA_PIN_MODIFY_LOCK                          1144 
#define IDS_CA_CARD_PAIR                                1145 
#define IDS_CA_WALLET_CHECK                             1146 
#define IDS_CA_SP_NAME1                                 1147 
#define IDS_CA_WALLET_USED                              1148 
#define IDS_CA_WALLET_LEFT                              1149 
#define IDS_CA_SENDER                                   1150 
#define IDS_CA_PASSWORD_PIN_ERROR                       1151 
#define IDS_CA_READ_MOTHER_CARD_FAILURE                 1152 
#define IDS_CA_OUT_OF_WORKTIME                          1153 
#define IDS_CA_LEVEL_TOO_LOW                            1154 
#define IDS_CA_NO_ENABLE1                               1155 
#define IDS_CA_CRYPTED_PROG_INSERT_SMC                  1156 
#define IDS_CA_WORK_TIME_TIPS                           1157 
#define IDS_CA_E_APP_STOP                               1158 
#define IDS_CA_MODIFY_CTRLCODE                          1159 
#define IDS_CA_SET_MON_SON_CARD                         1160 
#define IDS_CA_CLEAR_PARENT_LOCK                        1161 
#define IDS_CA_ILLEGAL_AUTH                             1162 
#define IDS_CAS_E_CARD_LOCKED                           1163 
#define IDS_CA_OPERATE_CARD_FAIL                        1164 
#define IDS_CA_CARD_DATA_ERROR                          1165 
#define IDS_CAS_S_CARD_REMOVE                           1166 
#define IDS_CAS_PIN_CHANGED_SUCCESSFULLY                1167 
#define IDS_CA_PIN_INVALID2                             1168 
#define IDS_MINUTE2                                     1169 
#define IDS_CA_OVERDUE_TIME                             1170 
#define IDS_SLOT_ID2                                    1171 
#define IDS_CA_NO_RECORD_PRICE                          1172 
#define IDS_CA_RECORD_PRICE                             1173 
#define IDS_CA_PPV_FREE                                 1174 
#define IDS_CA_PPV_CHARGES                              1175 
#define IDS_CA_PPT_CHARGES                              1176 
#define IDS_CA_INTERVAL                                 1177 
#define IDS_BACK_DEDUCTIONS                             1178 
#define IDS_IPP_BUY_PIN_CODE_HELP_INFO                  1179 
#define IDS_IPP_BUY_NORECORDED_HELP_INFO                1180 
#define IDS_IPP_BUY_RECORDED_HELP_INFO                  1181 
#define IDS_IPP_BUY_OTHER_HELP_INFO                     1182 
#define IDS_INSERT_SMC                                  1183 
#define IDS_DIGIT_NOT_ENOUGH                            1184 
#define IDS_CA_IPPV_PURCHASED_SUCCESS                   1185 
#define IDS_CA_IPPT_PURCHASED_SUCCESS                   1186 
#define IDS_CA_CARD_NO_ROOM                             1187 
#define IDS_CA_POINT_NULL                               1188 
#define IDS_CA_NO_CARD_INVALID                          1189 
#define IDS_CA_PRICE_INVALID                            1190 
#define IDS_CA_NO_OPE_PURSE                             1191 
#define IDS_FEED                                        1192 
#define IDS_CA_STB_CADR_MATCH_SUCCESS                   1193 
#define IDS_CA_STB_CADR_DISMATCH_SUCCESS                1194 
#define IDS_CA_STB_CADR_NOT_MATCH                       1195 
#define IDS_CA_CARD_EXPIRE_TIME                         1196 
#define IDS_CA_OUT_RATING                               1197 
#define IDS_CA_OUT_WORKING_HOURS                        1198 
#define IDS_NO_ENOUGH_MONEY                             1199 
#define IDS_CRYPTED_PROG_INSERT_SMC                     1200 
#define IDS_AREA_ERROR                                  1201 
#define IDS_CA_CHECK_FAILED                             1202 
#define IDS_NO_ENTITLEMENT                              1203 
#define IDS_CONDITIAN_BAN                               1204 
#define IDS_CA_SWITCH_FREQ                              1205 
#define IDS_BLACKLIST                                   1206 
#define IDS_CA_CARD_STOPED                              1207 
#define IDS_CA_STB_REBOOT                               1208 
#define IDS_CA_NOT_TIME_FEED                            1209 
#define IDS_CA_CURRENT_VERSION                          1210 
#define IDS_CA_UPGRADE_VERSION                          1211 
#define IDS_CA_CARD_INIT_SUCCESS                        1212 
#define IDS_CA_ZONECODE_VALUUE                          1213 
#define IDS_CA_EIGENVALUE_INFO_1                        1214 
#define IDS_AGE_LIMIT_1                                 1215 
#define IDS_CA_SLOT_POINT_1                             1216 
#define IDS_CONSUME_POINT                               1217 
#define IDS_CA_POSTAL_POST                              1218 
#define IDS_CA_GROUP_NUMBER                             1219 
#define IDS_CA_CARD_PROVIDERS                           1220 
#define IDS_CA_CARD_SET                                 1221 
#define IDS_CA_FEED_PERIOD                              1222 
#define IDS_CA_FEED_ENCRY_PROGRAM                       1223 
#define IDS_CA_INSERT_SC                                1224 
#define IDS_CA_CARD_OUT                                 1225 
#define IDS_CA_ERROR_SC                                 1226 
#define IDS_CA_NOT_PRODER                               1227 
#define IDS_CA_INIT_FAIL                                1228 
#define IDS_CA_NO_OPEN_SC                               1229 
#define IDS_CA_BLACKOUT_1                               1230 
#define IDS_CA_APPLY_STOP                               1231 
#define IDS_CA_CARD_CLOSED                              1232 
#define IDS_CA_NOTE_MATCH                               1233 
#define IDS_CA_NOT_ENTILE                               1234 
#define IDS_CA_AREA_CONTROL                             1235 
#define IDS_CA_OUT_WORKTIME                             1236 
#define IDS_CA_OUT_LEVEL                                1237 
#define IDS_CA_OU_PERIOD                                1238 
#define IDS_CA_DATA_ERROR                               1239 
#define IDS_CA_NO_ENTILE_PROG                           1240 
#define IDS_CA_CW_ERROR                                 1241 
#define IDS_CA_MATCH_FAILED                             1242 
#define IDS_CA_CANCEL_MATCH_FAILED                      1243 
#define IDS_CA_ENTILE_FAILED                            1244 
#define IDS_CA_PROPERITY_ENTILED_FAILED                 1245 
#define IDS_CA_INSERT_MOTHER_SC                         1246 
#define IDS_CA_SC_ERROR_DESCRAM                         1247 
#define IDS_CA_NOT_MATCH_TIME                           1248 
#define IDS_CA_NOT_IPPV                                 1249 
#define IDS_CA_INIT_SC_OK                               1250 
#define IDS_CA_MATCH_SUCCESS                            1251 
#define IDS_CA_CANCEL_MATCH_SUCCESS                     1252 
#define IDS_CA_PROG_ENTILE_OK                           1253 
#define IDS_CA_PROPERITY_ENTILED_SUCCESS                1254 
#define IDS_CA_BIND_SUCCESS                             1255 
#define IDS_CA_CANCEL_BIND_SUCCESS                      1256 
#define IDS_CA_INSERT_CHILD_CARD_1                      1257 
#define IDS_CA_INSERT_MOTHER_SC_RIGHT                   1258 
#define IDS_CA_INSERT_CHILD_SC_RIGHT                    1259 
#define IDS_CA_IPPT_TIME_EXPIRED                        1260 
#define IDS_CA_CHILD_ENTILED_OK                         1261 
#define IDS_CA_ENTITLE_PROGARM_TOTAL                    1262 
#define IDS_TOTAL_PAGE                                  1263 
#define IDS_CA_PIN_SUMA_INVALID                         1264 
#define IDS_PASSWORD_CONFLICT                           1265 
#define IDS_VIDEO_QUALITY                               1266 
#define IDS_VIDEO_VIVID                                 1267 
#define IDS_HARDWARE_MOD                                1268 
#define IDS_SOFTWARE_MOD                                1269 
#define IDS_INSTALLATION_HELP_SCAN                      1270 
#define IDS_CA_EMM_ERROR                                1271 
#define IDS_CA_ECM_ERROR                                1272 
#define IDS_CA_RET_ECM_DATA_ERROR                       1273 
#define IDS_CA_RET_ECM_EMM_P1P2_ERROR                   1274 
#define IDS_CA_RET_ECM_EMM_P3_ERROR                     1275 
#define IDS_CA_NO_ECM_INFO                              1276 
#define IDS_CA_PAIRED_OTHERCARD_ERROR                   1277 
#define IDS_CA_PAIRED_OTHERSTB_ERROR                    1278 
#define IDS_CA_MASTERSLAVE_PAIRED_OK_DONG               1279 
#define IDS_CA_MASTERSLAVE_NEEDPAIRED                   1280 
#define IDS_CA_CANCEL_PAIRED_OK                         1281 
#define IDS_CA_CARD_ZONE_INVALID                        1282 
#define IDS_CA_CARD_ZONE_CHECK_ENTER                    1283 
#define IDS_CA_CARD_ZONE_CHECK_OK                       1284 
#define IDS_CA_ZONECDN_LIMIT_CTRL_DISABLE               1285 
#define IDS_CA_MASTERSLAVE_PAIRED_UPDATE                1286 
#define IDS_CA_ECM_EMM_RET_UNKNOWN_ERROR                1287 
#define IDS_CA_USERCDN_LIMIT_CTRL_DISABLE               1288 
#define IDS_CA_ZONECDN_LIMIT_CTRL_ENABLE                1289 
#define IDS_OPERATOR_FAILED                             1290 
#define IDS_FOUR_YEARS_UP                               1291 
#define IDS_EIGHT_YEARS_UP                              1292 
#define IDS_TWELVE_YEARS_UP                             1293 
#define IDS_SIXTEEN_YEARS_UP                            1294 
#define IDS_ENTITLE_START_DATE                          1295 
#define IDS_ENTITLE_END_DATE                            1296 
#define IDS_ENTITLE_PRODUCT_PRICE                       1297 
#define IDS_WORK_TIME_ENABLE                            1298 
#define IDS_CAS_C_ACTIVE_CHILD_CARD                     1299 
#define IDS_CAS_E_PROG_UNAUTH2                          1300 
#define IDS_CAS_C_USERCDN_LIMIT_CTRL_ENABLE2            1301 
#define IDS_CAS_E_CARD_INIT_INSTALL                     1302 
#define IDS_CAS_E_CARD_INSTALLING                       1303 
#define IDS_CAS_E_CADR_NO_MONEY2                        1304 
#define IDS_CAS_E_CARD_REPAIR                           1305 
#define IDS_CAS_E_CARD_STOP                             1306 
#define IDS_CAS_E_CARD_LOGOUT                           1307 
#define IDS_CAS_E_CARD_OUT_WORK_TIME2                   1308 
#define IDS_CAS_E_PROG_LEVEL_LOWER                      1309 
#define IDS_CAS_E_CARD_MONEY_LACK                       1310 
#define IDS_CAS_E_CADR_TEMP_ACT                         1311 
#define IDS_CAS_E_CARD_EXPIRED                          1312 
#define IDS_CAS_E_CARD_PARTNER_FAILED2                  1313 
#define IDS_CAS_S_MOTHER_CARD_REGU_INSERT2              1314 
#define IDS_CAS_S_MOTHER_CARD_INVALID                   1315 
#define IDS_CAS_S_SON_CARD_REGU_INSERT2                 1316 
#define IDS_CAS_S_SON_CARD_INVALID                      1317 
#define IDS_CAS_S_MOTHER_SON_CARD_NOT_PAIR              1318 
#define IDS_CAS_S_MOTHER_CARD_COMM_FAIL                 1319 
#define IDS_CAS_S_SON_CARD_COMM_FAIL                    1320 
#define IDS_CAS_S_CARD_NOT_IN_ACTTIME                   1321 
#define IDS_CAS_S_CARD_INSERT_NEXT_CARD                 1322 
#define IDS_CAS_S_CARD_STOP_ACTIVE                      1323 
#define IDS_CAS_E_ILLEGAL_CARD2                         1324 
#define IDS_CAS_S_CARD_REMOVE2                          1325 
#define IDS_CAS_E_CARD_PG_ERROR                         1326 
#define IDS_CAS_C_CANCEL_PAIRED_OK                      1327 
#define IDS_CAS_C_CARD_ZONE_INVALID                     1328 
#define IDS_CAS_C_CARD_ZONE_CHECK_ENTER                 1329 
#define IDS_CAS_C_CARD_ZONE_CHECK_OK                    1330 
#define IDS_CAS_S_CARD_INIT_SUCCESS                     1331 
#define IDS_BOOKPG_START_1                              1332 
#define IDS_STB_NEED_UPDATE                             1333 
#define IDS_PPC_ENTITLE_INFO2                           1334 
#define IDS_PPV_ENTITLE_INFO2                           1335 
#define IDS_IPPV_ENTITLE_INFO                           1336 
#define IDS_PPT_ENTITLE_INFO                            1337 
#define IDS_CA_WALLET                                   1338 
#define IDS_MODIFY_PIN                                  1339 
#define IDS_CA_WATCHING_LEVEL                           1340 
#define IDS_EMAIL                                       1341 
#define IDS_UDRM_INFO                                   1342 
#define IDS_UDRM_MENU                                   1343 
#define IDS_PPC_IDENTIFICATION_NUMBER                   1344 
#define IDS_NAME3                                       1345 
#define IDS_PPV_IDENTIFICATION_NUMBER                   1346 
#define IDS_IPPV_IDENTIFICATION_NUMBER                  1347 
#define IDS_PPT_IDENTIFICATION_NUMBER                   1348 
#define IDS_PRICE_PER_PERIOD                            1349 
#define IDS_PERIOD_LENGTH                               1350 
#define IDS_UPDOWN_FLIP                                 1351 
#define IDS_CA_PURSE_BALANCE                            1352 
#define IDS_ENTER_OLD_PIN                               1353 
#define IDS_ENTER_NEW_PIN                               1354 
#define IDS_REPEAT_NEW_PIN                              1355 
#define IDS_PIN_CHANGED_SUCCESS                         1356 
#define IDS_PIN_CHANGED_FAILED                          1357 
#define IDS_ORDINARY_LEVEL                              1358 
#define IDS_CHILDREN_WATCH                              1359 
#define IDS_PARENTAL_GUIDANCE                           1360 
#define IDS_12_YEARS_OLD                                1361 
#define IDS_15_YEARS_OLD                                1362 
#define IDS_18_YEARS_OLD                                1363 
#define IDS_WATCHING_LEVEL_CHANGED_SUCCESS              1364 
#define IDS_WATCHING_LEVEL_CHANGED_FAILED               1365 
#define IDS_MAIL_TITLE                                  1366 
#define IDS_SEND_TIME                                   1367 
#define IDS_STATUS                                      1368 
#define IDS_READ                                        1369 
#define IDS_UNREAD                                      1370 
#define IDS_TITLE                                       1371 
#define IDS_CONTENT                                     1372 
#define IDS_OSD_MESSAGE                                 1373 
#define IDS_PURCHASE_POINTS                             1374 
#define IDS_IPPV_INFO                                   1375 
#define IDS_ORDER_PROGRAME                              1376 
#define IDS_SCRAMBLE_CYCLE                              1377 
#define IDS_POINT_PER                                   1378 
#define IDS_PPT_INFO                                    1379 
#define IDS_UDRM_USER_ID                                1380 
#define IDS_UDRM_REGIONAL_CONTROL_INFO                  1381 
#define IDS_UDRM_VERSION                                1382 
#define IDS_ADULT_BARRING_PROGRAM_PIN                   1383 
#define IDS_PIN_ERROR                                   1384 
#define IDS_NONSCRAMBLED_PROGRAM                        1385 
#define IDS_UTI_CHIP_ERROR                              1386 
#define IDS_UTI_CHIP_INVALID                            1387 
#define IDS_NO_OPERATION                                1388 
#define IDS_NVRAM_ERROR                                 1389 
#define IDS_NO_SIGNAL                                   1390 
#define IDS_PROGRAM_ABNORMAL                            1391 
#define IDS_NO_AUTHORIZATION                            1392 
#define IDS_DESCRAMBLING_SUCCESS                        1393 
#define IDS_LIMIT_BROADCAST_AREA                        1394 
#define IDS_ADULT_BARRING_PROGRAM                       1395 
#define IDS_FINGERPRINT_DISPLAY                         1396 
#define IDS_BUY_CREDITS_RESTRICTED                      1397 
#define IDS_PROGRAM_PREVIEW                             1398 
#define IDS_PRODUCT_PURCHASED                           1399 
#define IDS_MAX_AUTHORIZATION                           1400 
#define IDS_NOT_ACCOUNT                                 1401 
#define IDS_PASSWORD_RESET                              1402 
#define IDS_CONNECTION_SERVER_FAILED                    1403 
#define IDS_PROTECTED_DRM                               1404 
#define IDS_UTI_CHIP_LOCK                               1405 
#define IDS_UTI_CHIP_UNLOCK                             1406 
#define IDS_AREA_ERROR_RESTART                          1407 
#define IDS_CARD_ERR_DATA                               1408 
#define IDS_CARD_STOP                                   1409 
#define IDS_CA_CARD_PIN_LOCK                            1410 
#define IDS_DATA_BROADCAST                              1411 
#define IDS_CUSTOMER_ID                                 1412 
#define IDS_IMPORT_USB_PRESET_CHANNEL                   1413 
#define IDS_IMPORT_USB_PRESET_CHANNEL_SUCCESS           1414 
#define IDS_IMPORT_USB_PRESET_CHANNEL_FAIL              1415 
#define IDS_IMPORTING_PRESET_CHANNEL                    1416 
#define IDS_USB_IMPORT                                  1417 
#define IDS_USB_EXPORT                                  1418 
#define IDS_EXPORTING_PRESET_CHANNEL                    1419 
#define IDS_LAST_CHANNEL                                1420 
#define IDS_FIRST_CHANNEL                               1421 
#define IDS_DEFAULT_VOLUME                              1422 
#define IDS_LAST_VOLUME                                 1423 
#define IDS_POWER_CHANNEL_SETTING                       1424 
#define IDS_VOLUME_LEVER                                1425 
#define IDS_DISPLAY_SETTING                             1426 
#define IDS_MANUAL_SETTING                              1427 
#define IDS_DEFAULT_SETTING                             1428 
#define IDS_VOLUME_DEFAULT_SET                          1429 
#define IDS_BRIGHT                                      1430 
#define IDS_CONTRAST                                    1431 
#define IDS_SATURATION                                  1432 
#define IDS_TV_RADIO_AISAT                              1433 
#define IDS_CA_CARD_READ_FAIL                           1434 
#define IDS_CA_ENTITLE_EXPIRE                           1435 
#define IDS_CA_RECORD_CONTROL                           1436 
#define IDS_CA_PPC_PROG                                 1437 
#define IDS_CA_PPV_PROG_AUTHOR_SUCCESSED                1438 
#define IDS_CA_PPV_PROG_AUTHOR_FAILED                   1439 
#define IDS_CA_PPC_PROG_AUTHOR_SUCCESSED                1440 
#define IDS_CA_PPC_PROG_AUTHOR_FAILED                   1441 
#define IDS_CA_REMAIN_DAY                               1442 
#define IDS_CA_CARD_MATCH_CANCEL_FAILED                 1443 
#define IDS_CA_PURSE_FULL                               1444 
#define IDS_CA_CARD_VERSION_ERROR                       1445 
#define IDS_CA_IPPV_ZERO_EVENT                          1446 
#define IDS_CA_IPPV_EVENT_ID                            1447 
#define IDS_CA_IPPV_EVENT_ID1                           1448 
#define IDS_MSG_CA_CARD_IN1                             1449 
#define IDS_MSG_CA_CARD_OUT1                            1450 
#define IDS_CA_PROG_AUTHOR_SUCCESSED                    1451 
#define IDS_STB_ID_ORIGINAL                             1452 
#define IDS_STB_ID_OPTIONAL1                            1453 
#define IDS_STB_ID_OPTIONAL2                            1454 
#define IDS_STB_ID_SETTING                              1455 
#define IDS_STB_ID_TYPE                                 1456 
#define IDS_STB_ID_NUM                                  1457 
#define IDS_NO_MOSAIC                                   1458 
#define IDS_EXIT_MOSAIC                                 1459 
#define IDS_MOSAIC                                      1460 
#define IDS_FN                                          1461 

#endif
