/********************************************************************************************/
/* Copyright (c) 2014 Montage Technology Group Limited and its affiliated companies         */
/* Montage Proprietary and Confidential                                                     */
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/********************************************************************************************/
/****************************************************************************

 ****************************************************************************/
#ifndef __UI_AUTO_SEARCH_H__
#define __UI_AUTO_SEARCH_H__

/* coordinate */
#define AUTO_SEARCH_CONT_X			((SCREEN_WIDTH-AUTO_SEARCH_CONT_W)/2)
#define AUTO_SEARCH_CONT_W        COMM_BG_W
#define AUTO_SEARCH_CONT_H			420

#define AUTO_SEARCH_V_GAP               15

//specify tp frm
#define AUTO_SEARCH_SPECIFY_TP_FRM_X     100//50
#define AUTO_SEARCH_SPECIFY_TP_FRM_Y     COMM_ITEM_OY_IN_ROOT//120
#define AUTO_SEARCH_SPECIFY_TP_FRM_W     (AUTO_SEARCH_CONT_W - 2 * AUTO_SEARCH_SPECIFY_TP_FRM_X)
#define AUTO_SEARCH_SPECIFY_TP_FRM_H     (AUTO_SEARCH_ITEM_CNT * (AUTO_SEARCH_ITEM_H + AUTO_SEARCH_ITEM_V_GAP) + 20)//210

//searching info frm
#define AUTO_SEARCH_SIG_INFO_FRM_X        70
#define AUTO_SEARCH_SIG_INFO_FRM_Y        (AUTO_SEARCH_SPECIFY_TP_FRM_Y + AUTO_SEARCH_SPECIFY_TP_FRM_H \
                                                                            + AUTO_SEARCH_V_GAP)  //395
#define AUTO_SEARCH_SIG_INFO_FRM_W        (COMM_BG_W - AUTO_SEARCH_SIG_INFO_FRM_X)
#define AUTO_SEARCH_SIG_INFO_FRM_H        140

//signal strength name
#define AUTO_SEARCH_SIG_STRENGTH_NAME_X       70
#define AUTO_SEARCH_SIG_STRENGTH_NAME_Y       20
#define AUTO_SEARCH_SIG_STRENGTH_NAME_W       150
#define AUTO_SEARCH_SIG_STRENGTH_NAME_H       30

//signal strength percent
#define AUTO_SEARCH_SIG_STRENGTH_PERCENT_X    (AUTO_SEARCH_SIG_STRENGTH_NAME_X + AUTO_SEARCH_SIG_STRENGTH_NAME_W)
#define AUTO_SEARCH_SIG_STRENGTH_PERCENT_Y    AUTO_SEARCH_SIG_STRENGTH_NAME_Y
#define AUTO_SEARCH_SIG_STRENGTH_PERCENT_W    90
#define AUTO_SEARCH_SIG_STRENGTH_PERCENT_H    30

//signal strength pbar
#define AUTO_SEARCH_SIG_STRENGTH_PBAR_X       (AUTO_SEARCH_SIG_STRENGTH_PERCENT_X + AUTO_SEARCH_SIG_STRENGTH_PERCENT_W)
#define AUTO_SEARCH_SIG_STRENGTH_PBAR_Y       (AUTO_SEARCH_SIG_STRENGTH_PERCENT_Y + (AUTO_SEARCH_SIG_STRENGTH_NAME_H - AUTO_SEARCH_SIG_STRENGTH_PERCENT_H)/2)
#define AUTO_SEARCH_SIG_STRENGTH_PBAR_W       (COMM_BG_W - 2 * (AUTO_SEARCH_SIG_INFO_FRM_X + AUTO_SEARCH_SIG_STRENGTH_NAME_X) - AUTO_SEARCH_SIG_STRENGTH_NAME_W - AUTO_SEARCH_SIG_STRENGTH_PERCENT_W)
#define AUTO_SEARCH_SIG_STRENGTH_PBAR_H       16

//signal BER name
#define AUTO_SEARCH_SIG_BER_NAME_X       AUTO_SEARCH_SIG_STRENGTH_NAME_X
#define AUTO_SEARCH_SIG_BER_NAME_Y       (AUTO_SEARCH_SIG_STRENGTH_NAME_Y + AUTO_SEARCH_SIG_STRENGTH_NAME_H + AUTO_SEARCH_V_GAP)
#define AUTO_SEARCH_SIG_BER_NAME_W       AUTO_SEARCH_SIG_STRENGTH_NAME_W
#define AUTO_SEARCH_SIG_BER_NAME_H       AUTO_SEARCH_SIG_STRENGTH_NAME_H

//signal BER percent
#define AUTO_SEARCH_SIG_BER_PERCENT_X    AUTO_SEARCH_SIG_STRENGTH_PERCENT_X
#define AUTO_SEARCH_SIG_BER_PERCENT_Y    AUTO_SEARCH_SIG_BER_NAME_Y
#define AUTO_SEARCH_SIG_BER_PERCENT_W    AUTO_SEARCH_SIG_STRENGTH_PERCENT_W
#define AUTO_SEARCH_SIG_BER_PERCENT_H    AUTO_SEARCH_SIG_STRENGTH_PERCENT_H

//signal BER pbar
#define AUTO_SEARCH_SIG_BER_PBAR_X       AUTO_SEARCH_SIG_STRENGTH_PBAR_X
#define AUTO_SEARCH_SIG_BER_PBAR_Y       (AUTO_SEARCH_SIG_BER_NAME_Y + (AUTO_SEARCH_SIG_BER_NAME_H - AUTO_SEARCH_SIG_BER_PBAR_H)/2)
#define AUTO_SEARCH_SIG_BER_PBAR_W       AUTO_SEARCH_SIG_STRENGTH_PBAR_W
#define AUTO_SEARCH_SIG_BER_PBAR_H       AUTO_SEARCH_SIG_STRENGTH_PBAR_H

//signal SNR name
#define AUTO_SEARCH_SIG_SNR_NAME_X       AUTO_SEARCH_SIG_STRENGTH_NAME_X
#define AUTO_SEARCH_SIG_SNR_NAME_Y       (AUTO_SEARCH_SIG_BER_NAME_Y + AUTO_SEARCH_SIG_BER_NAME_H + AUTO_SEARCH_V_GAP)
#define AUTO_SEARCH_SIG_SNR_NAME_W       AUTO_SEARCH_SIG_STRENGTH_NAME_W
#define AUTO_SEARCH_SIG_SNR_NAME_H       AUTO_SEARCH_SIG_STRENGTH_NAME_H

//signal SNR percent
#define AUTO_SEARCH_SIG_SNR_PERCENT_X    AUTO_SEARCH_SIG_STRENGTH_PERCENT_X
#define AUTO_SEARCH_SIG_SNR_PERCENT_Y    AUTO_SEARCH_SIG_SNR_NAME_Y
#define AUTO_SEARCH_SIG_SNR_PERCENT_W    AUTO_SEARCH_SIG_STRENGTH_PERCENT_W
#define AUTO_SEARCH_SIG_SNR_PERCENT_H    AUTO_SEARCH_SIG_STRENGTH_PERCENT_H

//signal SNR pbar
#define AUTO_SEARCH_SIG_SNR_PBAR_X       AUTO_SEARCH_SIG_STRENGTH_PBAR_X
#define AUTO_SEARCH_SIG_SNR_PBAR_Y       (AUTO_SEARCH_SIG_SNR_NAME_Y + (AUTO_SEARCH_SIG_SNR_NAME_H - AUTO_SEARCH_SIG_SNR_PBAR_H)/2)
#define AUTO_SEARCH_SIG_SNR_PBAR_W       AUTO_SEARCH_SIG_STRENGTH_PBAR_W
#define AUTO_SEARCH_SIG_SNR_PBAR_H       AUTO_SEARCH_SIG_STRENGTH_PBAR_H

#define AUTO_SEARCH_ITEM_CNT		4
#define AUTO_SEARCH_ITEM_X			20 //COMM_ITEM_OX_IN_ROOT
#define AUTO_SEARCH_ITEM_Y			10 //COMM_ITEM_OY_IN_ROOT
#define AUTO_SEARCH_ITEM_LW		COMM_ITEM_LW
#define AUTO_SEARCH_ITEM_RW		(COMM_ITEM_MAX_WIDTH - AUTO_SEARCH_ITEM_LW)
#define AUTO_SEARCH_ITEM_H			COMM_ITEM_H
#define AUTO_SEARCH_ITEM_V_GAP		4 //16

#define RSI_AUTO_SEARCH_PBAR_BG           RSI_PROGRESS_BAR_BG
#define RSI_AUTO_SEARCH_PBAR_MID          RSI_PROGRESS_BAR_MID_ORANGE

#define AUTO_SEARCH_MAX_CNT    10

/* rect style */
#define RSI_AUTO_SEARCH_FRM		RSI_COMMON_RECT1
/* font style */

/* others */

RET_CODE open_auto_search (u32 para1, u32 para2);

RET_CODE preopen_auto_search(u32 para1, u32 para2);

#endif

