/********************************************************************************************/
/* Copyright (c) 2014 Montage Technology Group Limited and its affiliated companies         */
/* Montage Proprietary and Confidential                                                     */
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/********************************************************************************************/
/****************************************************************************

 ****************************************************************************/
#ifndef _UI_EPG_FIND_H_
#define _UI_EPG_FIND_H_

#include "ui_common.h"

/*coordinates*/
#define EPG_FIND_MENU_X  ((COMM_BG_W - EPG_FIND_MENU_W)/2)
#define EPG_FIND_MENU_Y  ((COMM_BG_H - EPG_FIND_MENU_H)/2)
#define EPG_FIND_MENU_W  634//SCREEN_WIDTH
#define EPG_FIND_MENU_H  420//388//SCREEN_HEIGHT

#define EPG_FIND_ICON_X  0
#define EPG_FIND_ICON_Y  0
#define EPG_FIND_ICON_W  80
#define EPG_FIND_ICON_H  80

#define EPG_FIND_TOP_LINE_X  60
#define EPG_FIND_TOP_LINE_Y  70
#define EPG_FIND_TOP_LINE_W  490//540
#define EPG_FIND_TOP_LINE_H  18

#define EPG_FIND_BOTTOM_LINE_X  EPG_FIND_TOP_LINE_X
#define EPG_FIND_BOTTOM_LINE_Y  270
#define EPG_FIND_BOTTOM_LINE_W  EPG_FIND_TOP_LINE_W
#define EPG_FIND_BOTTOM_LINE_H  18

#define EPG_FIND_DETAIL_X  110
#define EPG_FIND_DETAIL_Y  90
#define EPG_FIND_DETAIL_W  400//440
#define EPG_FIND_DETAIL_H  180

#define EPG_FIND_DETAIL_PGX  0
#define EPG_FIND_DETAIL_PGY  0
#define EPG_FIND_DETAIL_PGW  240
#define EPG_FIND_DETAIL_PGH  30

#define EPG_FIND_DETAIL_EVTNX  0
#define EPG_FIND_DETAIL_EVTNY  (EPG_FIND_DETAIL_PGY + EPG_FIND_DETAIL_PGH + EPG_FIND_DETAIL_VGAP)
#define EPG_FIND_DETAIL_EVTNW  EPG_FIND_DETAIL_W
#define EPG_FIND_DETAIL_EVTNH  EPG_FIND_DETAIL_PGH

#define EPG_FIND_DETAIL_EVTTX  0
#define EPG_FIND_DETAIL_EVTTY  (EPG_FIND_DETAIL_EVTNY + EPG_FIND_DETAIL_EVTNH + EPG_FIND_DETAIL_VGAP)
#define EPG_FIND_DETAIL_EVTTW  (EPG_FIND_DETAIL_W - 4*EPG_FIND_DETAIL_TYPEW)
#define EPG_FIND_DETAIL_EVTTH  EPG_FIND_DETAIL_PGH

#define EPG_FIND_DETAIL_SHORTX  0
#define EPG_FIND_DETAIL_SHORTY  (EPG_FIND_DETAIL_EVTTY + EPG_FIND_DETAIL_EVTTH + EPG_FIND_DETAIL_VGAP)
#define EPG_FIND_DETAIL_SHORTW  EPG_FIND_DETAIL_W
#define EPG_FIND_DETAIL_SHORTH  (2 * EPG_FIND_DETAIL_PGH + 10)

//
#define EPG_FIND_DETAIL_TYPEX  (EPG_FIND_DETAIL_EVTTX+EPG_FIND_DETAIL_EVTTW)
#define EPG_FIND_DETAIL_TYPEY  EPG_FIND_DETAIL_EVTTY
#define EPG_FIND_DETAIL_TYPEW  50
#define EPG_FIND_DETAIL_TYPEH  EPG_FIND_DETAIL_PGH

#define EPG_FIND_DETAIL_SCRAMBLEX  (EPG_FIND_DETAIL_TYPEX+EPG_FIND_DETAIL_TYPEW)
#define EPG_FIND_DETAIL_SCRAMBLEY  EPG_FIND_DETAIL_TYPEY
#define EPG_FIND_DETAIL_SCRAMBLEW  EPG_FIND_DETAIL_TYPEW
#define EPG_FIND_DETAIL_SCRAMBLEH  EPG_FIND_DETAIL_TYPEH

#define EPG_FIND_DETAIL_AGEX  (EPG_FIND_DETAIL_TYPEX+2*EPG_FIND_DETAIL_TYPEW)
#define EPG_FIND_DETAIL_AGEY  EPG_FIND_DETAIL_TYPEY
#define EPG_FIND_DETAIL_AGEW  EPG_FIND_DETAIL_TYPEW
#define EPG_FIND_DETAIL_AGEH  EPG_FIND_DETAIL_TYPEH

#define EPG_FIND_DETAIL_RESERVEX  (EPG_FIND_DETAIL_TYPEX+3*EPG_FIND_DETAIL_TYPEW)
#define EPG_FIND_DETAIL_RESERVEY  EPG_FIND_DETAIL_TYPEY
#define EPG_FIND_DETAIL_RESERVEW  EPG_FIND_DETAIL_TYPEW
#define EPG_FIND_DETAIL_RESERVEH  EPG_FIND_DETAIL_TYPEH


#define EPG_FIND_DETAIL_VGAP 4

#define EPG_FIND_PREV_X  560//610
#define EPG_FIND_PREV_Y  72//80
#define EPG_FIND_PREV_W  320//270
#define EPG_FIND_PREV_H  212//204

#define EPG_FIND_TIME_X  700
#define EPG_FIND_TIME_Y  20
#define EPG_FIND_TIME_W  170
#define EPG_FIND_TIME_H  36

//find condition
#define EPG_FIND_CONDITION_MBOX_X  80
#define EPG_FIND_CONDITION_MBOX_Y  290
#define EPG_FIND_CONDITION_MBOX_W  180
#define EPG_FIND_CONDITION_MBOX_H  252

//
//keyboard container
#define EPG_FIND_EDIT_CONTX 271
#define EPG_FIND_EDIT_CONTY 0
#define EPG_FIND_EDIT_CONTW 392
#define EPG_FIND_EDIT_CONTH 554

//find result list
#define EPG_FIND_LIST_EVENTX  260
#define EPG_FIND_LIST_EVENTY  290
#define EPG_FIND_LIST_EVENTW  626
#define EPG_FIND_LIST_EVENTH  215

//help
#define EPG_FIND_HELP_X  60 
#define EPG_FIND_HELP_Y  530
#define EPG_FIND_HELP_W  800
#define EPG_FIND_HELP_H  28

#define EPG_FIND_VGAP 6//4
#define EPG_FIND_HGAP 4

//genre container
#define EPG_FIND_GENRE_CONTX (EPG_FIND_CONDITION_MBOX_X + EPG_FIND_CONDITION_MBOX_W)
#define EPG_FIND_GENRE_CONTY 70
#define EPG_FIND_GENRE_CONTW 640
#define EPG_FIND_GENRE_CONTH 370
//genre title
#define EPG_FIND_GENRE_TITLEX ((EPG_FIND_GENRE_CONTW - EPG_FIND_GENRE_TITLEW)/2)
#define EPG_FIND_GENRE_TITLEY 0
#define EPG_FIND_GENRE_TITLEW 100
#define EPG_FIND_GENRE_TITLEH 36
//genre list left
#define EPG_FIND_GENRE_LLISTX 0
#define EPG_FIND_GENRE_LLISTY EPG_FIND_GENRE_TITLEH
#define EPG_FIND_GENRE_LLISTW 300
#define EPG_FIND_GENRE_LLISTH (EPG_FIND_GENRE_CONTH - EPG_FIND_GENRE_LLISTY)
//left sbar
#define EPG_FIND_GENRE_LSBARX (EPG_FIND_GENRE_LLISTW + EPG_FIND_GENRE_LLISTX)
#define EPG_FIND_GENRE_LSBARY EPG_FIND_GENRE_TITLEH
#define EPG_FIND_GENRE_LSBARW SBAR_WIDTH
#define EPG_FIND_GENRE_LSBARH EPG_FIND_GENRE_LLISTH
//genre list right
#define EPG_FIND_GENRE_RLISTX (EPG_FIND_GENRE_LLISTW + EPG_FIND_GENRE_LLISTX +EPG_FIND_GENRE_LSBARW)
#define EPG_FIND_GENRE_RLISTY EPG_FIND_GENRE_TITLEH
#define EPG_FIND_GENRE_RLISTW 300
#define EPG_FIND_GENRE_RLISTH (EPG_FIND_GENRE_CONTH - EPG_FIND_GENRE_RLISTY)
//right sbar
#define EPG_FIND_GENRE_RSBARX (EPG_FIND_GENRE_RLISTW + EPG_FIND_GENRE_RLISTX)
#define EPG_FIND_GENRE_RSBARY EPG_FIND_GENRE_TITLEH
#define EPG_FIND_GENRE_RSBARW SBAR_WIDTH
#define EPG_FIND_GENRE_RSBARH EPG_FIND_GENRE_RLISTH

//time&day container
#define EPG_FIND_TD_CONTX (EPG_FIND_CONDITION_MBOX_X + EPG_FIND_CONDITION_MBOX_W)
#define EPG_FIND_TD_CONTY 200
#define EPG_FIND_TD_CONTW 500
#define EPG_FIND_TD_CONTH 320
//time text
#define EPG_FIND_TD_TIME_TEXTX 20
#define EPG_FIND_TD_TIME_TEXTY 100
#define EPG_FIND_TD_TIME_TEXTW 160
#define EPG_FIND_TD_TIME_TEXTH 36
//day text
#define EPG_FIND_TD_DAY_TEXTX 20
#define EPG_FIND_TD_DAY_TEXTY 160
#define EPG_FIND_TD_DAY_TEXTW 160
#define EPG_FIND_TD_DAY_TEXTH 36
//ok text
#define EPG_FIND_TD_OK_TEXTX 20
#define EPG_FIND_TD_OK_TEXTY 220
#define EPG_FIND_TD_OK_TEXTW 80
#define EPG_FIND_TD_OK_TEXTH 36
//cancel text
#define EPG_FIND_TD_CANCEL_TEXTX 100
#define EPG_FIND_TD_CANCEL_TEXTY 220
#define EPG_FIND_TD_CANCEL_TEXTW 80
#define EPG_FIND_TD_CANCEL_TEXTH 36
//time list
#define EPG_FIND_TD_TIME_LISTX 200
#define EPG_FIND_TD_TIME_LISTY 0
#define EPG_FIND_TD_TIME_LISTW 300
#define EPG_FIND_TD_TIME_LISTH 200
//day list
#define EPG_FIND_TD_DAY_LISTX 200
#define EPG_FIND_TD_DAY_LISTY 0
#define EPG_FIND_TD_DAY_LISTW 300
#define EPG_FIND_TD_DAY_LISTH 300


/*rstyle*/
#define RSI_EPG_FIND_MENU    RSI_IGNORE
#define RSI_EPG_FIND_PREV  RSI_TV
#define RSI_EPG_FIND_DETAIL  RSI_PBACK
#define RSI_EPG_FIND_LIST_CONT RSI_PBACK
#define RSI_EPG_FIND_LIST  RSI_PBACK
#define RSI_EPG_FIND_SBAR          RSI_SCROLL_BAR_BG
#define RSI_EPG_FIND_SBAR_MID      RSI_SCROLL_BAR_MID


/*others*/
#define EPG_FIND_LIST_PAGE 5
#define EPG_FIND_GENRE_LLIST_PAGE 8
#define EPG_FIND_GENRE_RLIST_PAGE 8
#define EPG_FIND_TIME_LIST_PAGE 5
#define EPG_FIND_DAY_LIST_PAGE 8

#define EPG_FIND_LIST_FIELD 4
#define EPG_FIND_GENRE_LLIST_FIELD 2
#define EPG_FIND_GENRE_RLIST_FIELD 1
#define EPG_FIND_TIME_LIST_FIELD 1
#define EPG_FIND_DAY_LIST_FIELD 1


#define MAX_GENRE_LLIST_COUNT 12
#define MAX_GENRE_RLIST_COUNT 13
#define MAX_TIME_LIST_COUNT 5
#define MAX_DAY_LIST_COUNT 8



#define EPG_FIND_LCONT_MBOX_TOL  4
#define EPG_FIND_LCONT_MBOX_COL  4
#define EPG_FIND_LCONT_MBOX_ROW  1
#define EPG_FIND_LCONT_MBOX_HGAP  0
#define EPG_FIND_LCONT_MBOX_VGAP  0

#define EPG_FIND_INFO_MBOX_TOL  2
#define EPG_FIND_INFO_MBOX_COL  2
#define EPG_FIND_INFO_MBOX_ROW  1
#define EPG_FIND_INFO_MBOX_HGAP  4

#define SBAR_WIDTH 6
/*fstyle*/
#define FSI_EPG_FIND_INFO_MBOX FSI_WHITE

RET_CODE open_epg_find(u32 para1, u32 para2);

#endif
