/********************************************************************************************/
/* Copyright (c) 2014 Montage Technology Group Limited and its affiliated companies         */
/* Montage Proprietary and Confidential                                                     */
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/********************************************************************************************/
/****************************************************************************

****************************************************************************/
#include "ui_common.h"

rsc_rstyle_t c_tab[MAX_RSTYLE_CNT] =
{
  // RSI_IGNORE = 0
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_TRANSPARENT = 1
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER , C_TRANS}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_WINDOW_1 = 2
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_WINDOW_2 = 3
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_WINDOW_3 = 4
  { {R_ICON, IM_FRAME_ML}, {R_ICON, IM_FRAME_MT}, {R_ICON, IM_FRAME_MR}, {R_ICON, IM_FRAME_MD}, {R_FILL_ICON_TO_VERTEX, IM_BOX_1}, {R_ICON, IM_FRAME_LT}, {R_ICON, IM_FRAME_RT}, {R_ICON, IM_FRAME_RD}, {R_ICON, IM_FRAME_LD}},

  // RSI_ITEM_1_HL = 5
  { {R_ICON , IM_BUTTON1_L}, {R_IGNORE}, {R_ICON , IM_BUTTON1_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_ITEM_1_SH = 6
  { {R_ICON , IM_BUTTON2_L}, {R_IGNORE}, {R_ICON , IM_BUTTON2_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_SCROLL_BAR_BG = 7
  { {R_IGNORE}, {R_ICON , IM_SCROLL_BAR_BG_TOP}, {R_IGNORE}, {R_ICON , IM_SCROLL_BAR_BG_BOTTOM}, {R_FILL_ICON_TO_BORDER , IM_SCROLL_BAR_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_SCROLL_BAR_MID = 8
  { {R_IGNORE}, {R_ICON , IM_SCROLL_SCROLL_TOP}, {R_IGNORE}, {R_ICON , IM_SCROLL_SCROLL_BOTTOM}, {R_FILL_ICON_TO_BORDER , IM_SCROLL_SCROLL_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_VOLUME_BAR = 9
  { {R_ICON , IM_VOLUME_L}, {R_IGNORE}, {R_ICON , IM_VOLUME_R}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, IM_VOLUME_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  //RSI_LIST_FIELD_LEFT_HL = 10
  { {R_ICON , IM_BUTTON1_L}, {R_IGNORE}, {R_ICON , IM_BUTTON1_M}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_LIST_FIELD_LEFT_SH = 11
  { {R_ICON , IM_BUTTON2_L}, {R_IGNORE}, {R_ICON , IM_BUTTON2_M}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_LIST_FIELD_MID_HL = 12
  { {R_ICON , IM_BUTTON1_M}, {R_IGNORE}, {R_ICON , IM_BUTTON1_M}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_LIST_FIELD_MID_SH = 13
  { {R_ICON , IM_BUTTON2_M}, {R_IGNORE}, {R_ICON , IM_BUTTON2_M}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_LIST_FIELD_RIGHT_HL = 14
  { {R_ICON , IM_BUTTON1_M}, {R_IGNORE}, {R_ICON , IM_BUTTON1_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_LIST_FIELD_RIGHT_SH = 15
  { {R_COLOR, C_DEEP_BLUE}, {R_IGNORE}, {R_COLOR, C_DEEP_BLUE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER , C_DEEP_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_TV = 16
  { {R_ICON, IM_FRAME_ML}, {R_ICON, IM_FRAME_MT}, {R_ICON, IM_FRAME_MR}, {R_ICON, IM_FRAME_MD}, {R_FILL_RECT_TO_VERTEX, C_TRANS}, {R_ICON, IM_FRAME_LT}, {R_ICON, IM_FRAME_RT}, {R_ICON, IM_FRAME_RD}, {R_ICON, IM_FRAME_LD}},

  //RSI_LIGHT_BLUE_BACKGROUND = 17
  { {R_COLOR, C_LIGHT_BLUE}, {R_IGNORE}, {R_COLOR , C_LIGHT_BLUE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER , C_LIGHT_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_PROGRESS_BAR_BG = 18
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SIGNALBG_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_PROGRESS_BAR_MID_BLUE = 19
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SIGNAL_ORANGE_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_PROGRESS_BAR_MID_GREEN = 20
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SIGNAL_ORANGE_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_PROGRESS_BAR_MID_GRAY = 21
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SIGNAL_ORANGE_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_PROGRESS_BAR_MID_ORANGE = 22
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SIGNAL_ORANGE_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_PROGRESS_BAR_MID_RED = 23
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SIGNAL_ORANGE_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_LINE_03_MID = 24
  { {R_ICON , IM_BUTTON1_M}, {R_IGNORE}, {R_ICON, IM_BUTTON1_M}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_INFOR_WIN = 25
  { {R_ICON, IM_FRAME_ML}, {R_ICON, IM_FRAME_MT}, {R_ICON, IM_FRAME_MR}, {R_ICON, IM_FRAME_MD}, {R_FILL_ICON_TO_VERTEX, IM_BOX_1}, {R_ICON, IM_FRAME_LT}, {R_ICON, IM_FRAME_RT}, {R_ICON, IM_FRAME_RD}, {R_ICON, IM_FRAME_LD}},

  //RSI_VOLUME_WIN = 26
  { {R_ICON , IM_VOLUMEBG_L}, {R_IGNORE}, {R_ICON, IM_VOLUMEBG_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_VOLUMEBG_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_WHITE_FRM = 27
  {{R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_FILL_ICON_TO_VERTEX , IM_GAME_BOARD_MID}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_KEYBOARD_BAR = 28
  { {R_ICON , IM_KEYBOARD_BAR_LEFT}, {R_IGNORE}, {R_ICON , IM_KEYBOARD_BAR_RIGHT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_BAR_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_KEYBOARD_ITEM_HL = 29
  { {R_ICON, IM_KEYBOARD_ITEM_SELECT_V2_LR}, {R_IGNORE}, {R_ICON, IM_KEYBOARD_ITEM_SELECT_V2_LR}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_ITEM_SELECT_V2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_KEYBOARD_ITEM_SH = 30
  { {R_ICON, IM_KEYBOARD_ITEM_V2_LR}, {R_IGNORE}, {R_ICON, IM_KEYBOARD_ITEM_V2_LR}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_ITEM_V2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_PLAY_PBAR_BACK = 31
  { {IM_MEDIAPLAY_72}, {R_IGNORE}, {IM_MEDIAPLAY_72}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_MEDIAPLAY_72}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_PLAY_PBAR_FRONT = 32
  { {IM_MEDIAPLAY_70}, {R_IGNORE}, {IM_MEDIAPLAY_70}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_MEDIAPLAY_70}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_WINDOW_GAME = 33
  { {R_ICON, IM_FRAME_ML}, {R_ICON, IM_FRAME_MT}, {R_ICON, IM_FRAME_MR}, {R_ICON, IM_FRAME_MD}, {R_FILL_ICON_TO_VERTEX, IM_INDEX_BG}, {R_ICON, IM_FRAME_LT}, {R_ICON, IM_FRAME_RT}, {R_ICON, IM_FRAME_RD}, {R_ICON, IM_FRAME_LD}},

  //RSI_CHESS_HL = 34
  { {R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_FILL_ICON_TO_VERTEX , IM_GAME_BOARD_MID}, {R_ICON , IM_CHESS_SELECT_LEFTOP}, {R_ICON , IM_CHESS_SELECT_RIGHTOP}, {R_ICON , IM_CHESS_SELECT_RIGHTBOTTOM}, {R_ICON , IM_CHESS_SELECT_LEFTBOTTOM}},

  // RSI_ITEM_3_SH = 35
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER , C_DEEP_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_ITEM_2_SH = 36
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_VERTEX , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_LEFT_RIGHT_HL = 37
  { {R_ICON , IM_ARROW_BUTTON1_L}, {R_IGNORE}, {R_ICON , IM_BUTTON1_R_ARROW}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_T9EDIT_RIGHT_HL = 38
  { {R_ICON , IM_BUTTON1_M}, {R_IGNORE}, {R_ICON , IM_BUTTON1_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_T9EDIT_RIGHT_SH = 39
  { {R_ICON , IM_BUTTON2_M}, {R_IGNORE}, {R_ICON , IM_BUTTON2_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_T9EDIT_RIGHT_GRAY = 40
  { {R_ICON , IM_BUTTON3_M}, {R_IGNORE}, {R_ICON , IM_BUTTON3_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON3_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_COMMAN_BG = 41,
  { {R_ICON, IM_FRAME_ML}, {R_ICON, IM_FRAME_MT}, {R_ICON, IM_FRAME_MR}, {R_ICON, IM_FRAME_MD}, {R_FILL_ICON_TO_VERTEX, IM_BOX_2}, {R_ICON, IM_FRAME_LT}, {R_ICON, IM_FRAME_RT}, {R_ICON, IM_FRAME_RD}, {R_ICON, IM_FRAME_LD}},

  //RSI_COMMAN_MID_BG = 42,
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER , C_PINK}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_MMENUWIN01_BG = 43
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_INDEX_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_MMENUWIN01_BANNER_BG = 44
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_INDEX_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_MMENUWIN01_TIME_BG = 45
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_INDEX_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_LINE_EPG_SH = 46
  {{R_LINE1, C_WHITE}, {R_LINE1, C_WHITE}, {R_LINE1, C_WHITE}, {R_LINE1, C_WHITE}, {R_FILL_RECT_TO_BORDER , C_EPG_BLUE_SH}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  //RSI_LINE_EPG_HL = 47
  {{R_LINE1, C_WHITE}, {R_LINE1, C_WHITE}, {R_LINE1, C_WHITE}, {R_LINE1, C_WHITE}, {R_FILL_RECT_TO_BORDER , C_EPG_BLUE_HL}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_PBACK = 48
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_COPY_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_GAME_SELECT_HL = 49
  { {R_ICON , IM_ARROW_BUTTON1_L}, {R_IGNORE}, {R_ICON , IM_ARROW_BUTTON1_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_GAME_ITEM_HL = 50
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

 //RSI_ITEM_10_SH = 51
  { {R_LINE2,C_GOLD}, {R_LINE2,C_GOLD}, {R_LINE2,C_GOLD}, {R_LINE2,C_GOLD}, {R_COPY_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

 // RSI_ITEM_6_HL = 52
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SIGNAL_ORANGE_MIDDLE }, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},

 // RSI_ITEM_7_HL = 53
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER , C_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},

  //RSI_KEYBOARD_BAR_V2 = 54
  { {R_ICON , IM_KEYBOARD_BAR_LEFT}, {R_IGNORE}, {R_ICON , IM_KEYBOARD_BAR_RIGHT}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_BAR_MIDDLE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_KEYBOARD_LABEL_SH = 55,
  {{R_ICON, IM_KEYBOARD_TAB_BG}, {R_IGNORE}, {R_ICON , IM_KEYBOARD_TAB_BG}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_TAB_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_KEYBOARD_LABEL_HL = 56,
  { {R_ICON, IM_KEYBOARD_TAB_L}, {R_IGNORE}, {R_ICON, IM_KEYBOARD_TAB_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_TAB_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_KEYBOARD_BUTTON_SH = 57,
  { {R_ICON, IM_KEYBOARD_ITEM_V2_LR}, {R_IGNORE}, {R_ICON, IM_KEYBOARD_ITEM_V2_LR}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_ITEM_V2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_KEYBOARD_BUTTON_HL = 58,
  { {R_ICON, IM_KEYBOARD_ITEM_SELECT_V2_LR}, {R_IGNORE}, {R_ICON, IM_KEYBOARD_ITEM_SELECT_V2_LR}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_ITEM_SELECT_V2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },
 
  //RSI_TV_SMALL = 59
  { {R_ICON , IM_TVWIN01_L_SMALL}, {R_ICON , IM_TVWIN01_T_SMALL}, {R_ICON , IM_TVWIN01_R_SMALL}, {R_ICON , IM_TVWIN01_B_SMALL}, {R_FILL_RECT_TO_BORDER , C_TRANS}, {R_ICON , IM_TVWIN01_LT_SMALL}, {R_ICON , IM_TVWIN01_RT_SMALL}, {R_ICON , IM_TVWIN01_RB_SMALL}, {R_ICON , IM_TVWIN01_LB_SMALL} },

  //RSI_TIMESHIFT_PLAY_TIME_PBACK = 60,
  { {R_ICON, IM_INFORMATION_ICON_BG_L}, {R_IGNORE}, {R_ICON, IM_INFORMATION_ICON_BG_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_INFORMATION_ICON_BG_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_ITEM_GREEN_HL = 61,
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_SIGNAL_ORANGE_MIDDLE }, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},
   
  // RSI_MAINMENU_BG = 62,
  { {R_ICON, IM_INDEX_BG_ML}, {R_ICON, IM_INDEX_BG_MT}, {R_ICON, IM_INDEX_BG_MR}, {R_ICON, IM_INDEX_BG_MD}, {R_FILL_ICON_TO_VERTEX, IM_INDEX_BG}, {R_ICON, IM_INDEX_BG_LT}, {R_ICON, IM_INDEX_BG_RT}, {R_ICON, IM_INDEX_BG_RD}, {R_ICON, IM_INDEX_BG_LD} },
    
  // RSI_COMMON_RECT1 = 63,
  { {R_ICON, IM_FRAME_ML}, {R_ICON, IM_FRAME_MT}, {R_ICON, IM_FRAME_MR}, {R_ICON, IM_FRAME_MD}, {R_FILL_ICON_TO_VERTEX, IM_INDEX_BG}, {R_ICON, IM_FRAME_LT}, {R_ICON, IM_FRAME_RT}, {R_ICON, IM_FRAME_RD}, {R_ICON, IM_FRAME_LD}},
    
  //RSI_MENU_BTN_SH = 64,
  { {R_ICON , IM_BUTTON2_L}, {R_IGNORE}, {R_ICON , IM_BUTTON2_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },
    
  //RSI_MENU_BTN_HL = 65,
  { {R_ICON , IM_BUTTON1_L}, {R_IGNORE}, {R_ICON , IM_BUTTON1_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },
    
  // RSI_TITLE_BG = 66,
  { {R_ICON, IM_INDEX_BG_L}, {R_IGNORE}, {R_ICON, IM_INDEX_BG_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_INDEX_BG_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},
    
  //RSI_HELP_BG =67
  //{ {R_FILL_ICON_TO_VERTEX, IM_INDEX_BG_ML}, {R_IGNORE}, {R_FILL_ICON_TO_VERTEX, IM_INDEX_BG_MR}, {R_FILL_ICON_TO_VERTEX, IM_INDEX_BG_MD}, {R_FILL_ICON_TO_BORDER, IM_INDEX_BG}, {R_IGNORE}, {R_IGNORE}, {R_ICON, IM_INDEX_BG_RD },{R_ICON, IM_INDEX_BG_LD}},
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_INDEX_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},

  //RSI_MENU_ICON_SH = 68
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_BOX_1}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},
    
  //RSI_MENU_ICON_HL = 69
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_BOX_1}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE }},

  //RSI_DATE_SH = 70
  { {R_ICON , IM_BUTTON2_L}, {R_IGNORE}, {R_ICON , IM_BUTTON2_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON2_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },
 
  //RSI_DATE_HL= 71
  { {R_ICON , IM_BUTTON1_L}, {R_IGNORE}, {R_ICON , IM_BUTTON1_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON1_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_TRANSLUCENT = 72
  { {R_ICON, IM_FRAME_ML}, {R_ICON, IM_FRAME_MT}, {R_ICON, IM_FRAME_MR}, {R_ICON, IM_FRAME_MD}, {R_FILL_ICON_TO_VERTEX, IM_BOX_1}, {R_ICON, IM_FRAME_LT}, {R_ICON, IM_FRAME_RT}, {R_ICON, IM_FRAME_RD}, {R_ICON, IM_FRAME_LD}},

  // RSI_SMALL_LIST_TITLE = 73
  { {R_ICON , IM_BUTTON5_L_ARROW}, {R_IGNORE}, {R_ICON , IM_BUTTON5_R_ARROW}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON5_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },
  
  //RSI_MENU_ITEM_BG = 74
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_INDEX_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  //RSI_MAINMENU_TITLE_BG = 75
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_INDEX_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},
    
  //RSI_BLACK  = 76
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_VERTEX, C_BLACK}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},
    
  //RSI_BLUE = 77
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_VERTEX, C_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},
    
  //RSI_GRAY = 78
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_VERTEX, C_GRAY}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_OSD = 79
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_OSD_BACKGROUND}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_ROLL_OSD = 80
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_ROLL_OSD_BACKGROUND}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

 // RSI_FINGER_BACKGROUND = 81
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_FINGER_BACKGROUND}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_SMALL_LIST_TITLE_TRANS = 82
  { {R_ICON , IM_BUTTON4_L_ARROW}, {R_IGNORE}, {R_ICON , IM_BUTTON4_R_ARROW}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON4_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_WHITE =83
  {{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_FILL_RECT_TO_BORDER, C_WHITE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},

  //RSI_YELLOW =84
  {{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_FILL_RECT_TO_BORDER, C_YELLOW},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},
  
  //RSI_RED =85
  {{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_FILL_RECT_TO_BORDER, C_RED},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},  

//RSI_GREEN
  {{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_FILL_RECT_TO_BORDER, C_FONT_GREEN},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},  

  // RSI_FINGER_BACKGROUND_2
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_WHITE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

#ifdef ENABLE_NETWORK
  // RSI_POPUP_BG 12
  { {R_ICON , IM_POPUPBOX_ML}, {R_ICON , IM_POPUPBOX_MT}, {R_ICON , IM_POPUPBOX_MR}, {R_ICON , IM_POPUPBOX_MD}, {R_FILL_ICON_TO_VERTEX , IM_POPUPBOX_MM}, {R_ICON , IM_POPUPBOX_LT}, {R_ICON , IM_POPUPBOX_RT}, {R_ICON , IM_POPUPBOX_RD}, {R_ICON , IM_POPUPBOX_LD} },

  //RSI_ITEM_6 40
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_BUTTON_6_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_ITEM_2_HL 18
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_BUTTON_1_SELECT_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_ITEM_13_HL
  { {R_ICON , IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON , IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON , IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON , IM_PIC_YOUTUBE_BG_SELECT}, {R_FILL_RECT_TO_BORDER , C_BLACK}, {R_ICON ,IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON , IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON , IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON , IM_PIC_YOUTUBE_BG_SELECT} },

  // RSI_MAIN_BG 
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_BLACK}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_BOX_1 7
  { {R_ICON,IM_BOX_1_ML}, {R_ICON,IM_BOX_1_MT}, {R_ICON,IM_BOX_1_MR}, {R_ICON,IM_BOX_1_MD}, {R_FILL_ICON_TO_VERTEX,IM_BOX_1_MM}, {R_ICON,IM_BOX_1_LT}, {R_ICON,IM_BOX_1_RT}, {R_ICON,IM_BOX_1_RD}, {R_ICON,IM_BOX_1_LD}},

  // RSI_BOX_2 28
  { {R_ICON,IM_BOX_2_ML}, {R_ICON,IM_BOX_2_MT}, {R_ICON,IM_BOX_2_MR}, {R_ICON,IM_BOX_2_MD}, {R_FILL_ICON_TO_VERTEX,IM_BOX_2_MM}, {R_ICON,IM_BOX_2_LT}, {R_ICON,IM_BOX_2_RT}, {R_ICON,IM_BOX_2_RD}, {R_ICON,IM_BOX_2_LD}},

  //RSI_MV_POSTER_FRM_SH, 75
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_DARKER_GRAY},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},

  //RSI_MV_POSTER_FRM_HL,
  { {R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_FILL_RECT_TO_BORDER, C_RED},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},

  // RSI_SUBMENU_DETAIL_BG 4
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_BLACK}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_COMMON_TITLE 6
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER , IM_INPAGE_BANNER_BG_2}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_ITEM_11_SH 50
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER , C_DARKER_GRAY}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_ITEM_12_SH
  { {R_ICON, IM_PIC_YOUTUBE_BG}, {R_ICON, IM_PIC_YOUTUBE_BG}, {R_ICON, IM_PIC_YOUTUBE_BG}, {R_ICON, IM_PIC_YOUTUBE_BG}, {/*R_FILL_RECT_TO_BORDER , C_TRANS*//*R_IGNORE*/R_COPY_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_BLACK_FRM 10
  {{R_LINE2, C_BLACK}, {R_LINE2, C_BLACK}, {R_LINE2, C_BLACK}, {R_LINE2, C_BLACK}, {R_FILL_RECT_TO_BORDER , C_TRANS}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_MAP_SCROLL_BAR_BG
  { {R_IGNORE}, {R_ICON, IM_ICON_GOOGLEMAP_MAGNIFY}, {R_IGNORE}, {R_ICON, IM_ICON_GOOGLEMAP_SHRINK}, {R_FILL_ICON_TO_BORDER , IM_ICON_GOOGLEMAP_LINE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_MAP_SCROLL_BAR_MID
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_ICON, IM_ICON_GOOGLEMAP_ADJUST}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_MAIN_BG1 11
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_DARKER_GRAY}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_SMALL_LIST_ARROW = 56,
  { {R_ICON | R_CENTER, IM_SLISTARROW01_L}, {R_IGNORE}, {R_ICON | R_CENTER , IM_SLISTARROW01_R}, {R_IGNORE}, {R_COPY_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_PAGE_ARROW = 88,
  { {R_ICON | R_CENTER , IM_PAGEARROW_1}, {R_IGNORE}, {R_ICON | R_CENTER, IM_PAGEARROW_2}, {R_IGNORE}, {R_COPY_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_SMALL_LIST_ARROW_SELECT = 88,
  { {R_ICON | R_CENTER , IM_SLISTARROW02_L}, {R_IGNORE}, {R_ICON | R_CENTER, IM_SLISTARROW02_R}, {R_IGNORE}, {R_COPY_BG}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_ITEM_12_SH_TRANS  = 101
  { {R_ICON, IM_PIC_YOUTUBE_BG}, {R_ICON, IM_PIC_YOUTUBE_BG}, {R_ICON, IM_PIC_YOUTUBE_BG}, {R_ICON, IM_PIC_YOUTUBE_BG}, {R_FILL_RECT_TO_BORDER , C_TRANS/*R_IGNORE*/}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  //RSI_ITEM_12_HL_TRANS = 102
  { {R_ICON, IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON, IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON, IM_PIC_YOUTUBE_BG_SELECT}, {R_ICON, IM_PIC_YOUTUBE_BG_SELECT}, {R_FILL_RECT_TO_BORDER , C_TRANS}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_GRAY_FRM = 35 60
  {{R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_LINE2, C_WHITE}, {R_FILL_RECT_TO_BORDER , C_DARKER_GRAY}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_OTT_FRM_1_SH
	{
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_FILL_RECT_TO_BORDER , C_TRANS},
	  {R_IGNORE},
	  {R_IGNORE},
	  {R_IGNORE},
	  {R_IGNORE}
	},

  // RSI_OTT_FRM_1_HL
	{
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_FILL_RECT_TO_BORDER , C_TRANS},
	  {R_IGNORE},
	  {R_IGNORE},
	  {R_IGNORE},
	  {R_IGNORE}
	},

  // RSI_ITEM_8_SH
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_BUTTON_7_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  //RSI_ITEM_11_HL
  { {R_LINE4, C_RED}, {R_LINE4, C_RED}, {R_LINE4, C_RED}, {R_LINE4, C_RED}, {R_FILL_RECT_TO_BORDER , C_DARKER_GRAY}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},

  // RSI_OTT_PROGRESS_BAR_BG
	{
	    {R_ICON, IM_PROGRESS_BG_L},
	    {R_IGNORE},
		{R_ICON, IM_PROGRESS_BG_R}, 
		{R_IGNORE}, 
		{R_FILL_ICON_TO_BORDER , IM_PROGRESS_BG_M},
		{R_IGNORE}, 
		{R_IGNORE}, 
		{R_IGNORE}, 
		{R_IGNORE} 
	},

  // RSI_OTT_PROGRESS_BAR_MID
	{ 
		{R_ICON, IM_PROGRESS_L}, 
		{R_IGNORE},
		{R_ICON, IM_PROGRESS_R1},
		{R_IGNORE},
		{R_FILL_ICON_TO_BORDER , IM_PROGRESS_M},
		{R_IGNORE},
		{R_IGNORE},	  
		{R_IGNORE}, 
		{R_IGNORE} 
	},

  //RSI_PLAY_BUTTON_SH,
  { 
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE},
    {R_FILL_ICON_TO_VERTEX, IM_COLORBUTTON_BLUE_SELECT},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE}
  },
 
  //RSI_PLAY_BUTTON_HL, 74
  { 
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE},
    {R_FILL_ICON_TO_VERTEX, IM_COLORBUTTON_RED_SELECT},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE}
  },

  // RSI_OTT_FRM_1_RED_HL
	{
	  {R_LINE5, C_RED},
	  {R_LINE5, C_RED},
	  {R_LINE5, C_RED},
	  {R_LINE5, C_RED},
	  {R_FILL_RECT_TO_BORDER , C_TRANS},
	  {R_IGNORE},
	  {R_IGNORE},
	  {R_IGNORE},
	  {R_IGNORE}
	},
	
  //RSI_NM_CLASSIC_FRM_HL
	{
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_ICON, IM_BG_FOCUS_2},
	  {R_FILL_RECT_TO_BORDER , C_TRANS},
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_ICON, IM_BG_FOCUS_1},
	  {R_ICON, IM_BG_FOCUS_2},
	  {R_ICON, IM_BG_FOCUS_2},
	},

  //RSI_NM_CLASSIC_FRM_SH
	{
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_ICON, IM_BG_NORMAL_2},
	  {R_FILL_RECT_TO_BORDER , C_TRANS},
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_ICON, IM_BG_NORMAL_1},
	  {R_ICON, IM_BG_NORMAL_2},
	  {R_ICON, IM_BG_NORMAL_2},
	},

  // RSI_OTT_KEYBOARD_KEY_SH
  {
    {R_ICON, IM_KEYBOARD_1_L}, 
    {R_IGNORE},
    {R_ICON, IM_KEYBOARD_1_R}, 
    {R_IGNORE},
    {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_1_M},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE}
  },

  // RSI_OTT_KEYBOARD_KEY_HL
  {
    {R_ICON, IM_KEYBOARD_2_L}, 
    {R_IGNORE},
    {R_ICON, IM_KEYBOARD_2_R}, 
    {R_IGNORE},
    {R_FILL_ICON_TO_BORDER , IM_KEYBOARD_2_M},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE},
    {R_IGNORE}
  },

  // RSI_OTT_IM_SEARCH
	{ 
		{R_ICON, IM_SEARCHBOX_L}, 
		{R_IGNORE}, 
    {R_ICON, IM_SEARCHBOX_R}, 
    {R_IGNORE}, 
		{R_FILL_ICON_TO_BORDER, IM_SEARCHBOX_M}, 
		{R_IGNORE}, 
		{R_IGNORE}, 
		{R_IGNORE}, 
		{R_IGNORE} 
	},

  // RSI_ITEM_8_BG
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_BUTTON_7_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_ITEM_4_SH 20
  { {R_ICON, IM_BUTTON_4_L}, {R_IGNORE}, {R_ICON, IM_BUTTON_4_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_BUTTON_4_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },

  // RSI_ITEM_4_HL 21
  { {R_ICON, IM_BUTTON_4_SELECT_L}, {R_IGNORE}, {R_ICON, IM_BUTTON_4_SELECT_R}, {R_IGNORE}, {R_FILL_ICON_TO_BORDER, IM_BUTTON_4_SELECT_M}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE} },
#endif

  //RSI_OSD_BACKGROUND,
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_BORDER, C_DARKER_GRAY},{R_IGNORE},{R_IGNORE},{R_IGNORE},{R_IGNORE}},
  
  //RSI_SKY_BLUE
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_VERTEX, C_SKY_BLUE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},
  //RSI_LIGHT_RED
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_VERTEX, C_LIGHT_RED}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},
  //RSI_DEEP_GREEN
  { {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_FILL_RECT_TO_VERTEX, C_DEEP_GREEN}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}, {R_IGNORE}},
};

rsc_fstyle_t f_tab[MAX_FSTYLE_CNT] =
{
  //FSI_BLACK
  { FONT_ARIAL, C_BLACK, 0, 24, 24},
  //FSI_BLACK_18
  { FONT_ARIAL, C_BLACK, 0, 18, 18},
  //FSI_BLACK_24
  { FONT_ARIAL, C_BLACK, 0, 24, 24},
  //FSI_BLACK_32
  { FONT_ARIAL, C_BLACK, 0, 32, 32},
  //FSI_BLACK_48
  { FONT_ARIAL, C_BLACK, 0, 48, 48},
  //FSI_WHITE
  { FONT_ARIAL, C_WHITE, 0, 20, 20},
   //FSI_WHITE_18
  { FONT_ARIAL, C_WHITE, 0, 18, 18},
   //FSI_WHITE_24
  { FONT_ARIAL, C_WHITE, 0, 24, 24},
    //FSI_WHITE28
  { FONT_ARIAL, C_WHITE, 0, 28, 28},
  //FSI_WHITE_32
  { FONT_ARIAL, C_WHITE, 0, 32, 32},
  //FSI_WHITE_48
  { FONT_ARIAL, C_WHITE, 0, 48, 48},
  //FSI_RED
  { FONT_ARIAL, C_RED, 0, 24, 24},
  //FSI_RED_18
  { FONT_ARIAL, C_RED, 0, 18, 18},
  //FSI_RED_24
  { FONT_ARIAL, C_RED, 0, 24, 24},
  //FSI_RED_32
  { FONT_ARIAL, C_RED, 0, 32, 32},
  //FSI_RED_48
  { FONT_ARIAL, C_RED, 0, 48, 48},
  //FSI_GREEN
  { FONT_ARIAL, C_GREEN, 0, 24, 24},
  //FSI_BLUE
  { FONT_ARIAL, C_BLUE, 0, 24, 24},
  //FSI_DEEP_BLUE
  { FONT_ARIAL, C_DEEP_BLUE1, 0, 24, 24},
  //FSI_GRAY
  { FONT_ARIAL, C_GRAY, 0, 20, 20},
  //FSI_YELLOW
  { FONT_ARIAL, C_YELLOW, 0, 24, 24},
  //FSI_YELLOW_18
  { FONT_ARIAL, C_YELLOW, 0, 18, 18},
  //FSI_YELLOW_24
  { FONT_ARIAL, C_YELLOW, 0, 24, 24},
  //FSI_YELLOW_32
  { FONT_ARIAL, C_YELLOW, 0, 32, 32},
  //FSI_YELLOW_48
  { FONT_ARIAL, C_YELLOW, 0, 48, 48},
  //FSI_PROGLIST_BRIEF
  { FONT_ARIAL, C_PROGLIST_BRIEF, 0, 24, 24},
  //FSI_PROGBAR_BOTTOM
  { FONT_ARIAL, C_PROGBAR_BOTTOM, 0, 24, 24},
  //FSI_NUMBER
  { FONT_ARIAL, C_WHITE, 0, 24, 24},
   //FSI_FONT_BLUE
  { FONT_ARIAL, C_PINK, 0, 20, 20},
   //FSI_WHITE_INFO
  { FONT_ARIAL, C_WHITE, 0, 20, 20},
     //FSI_WHITE_TITLE
  { FONT_ARIAL, C_WHITE, 0, 28, 28},
     //FSI_DEEP_PURPLE
  { FONT_ARIAL, C_DEEP_PURPLE, 0, 28, 28},
    //FSI_LIGHT_GRAY
  { FONT_ARIAL, C_LIGHT_GRAY, 0, 24, 24},
  //FSI_OSD1
  { FONT_ARIAL, C_OSD_FONT, 0, 18, 18},
  //FSI_OSD2
  { FONT_ARIAL, C_OSD_FONT, 0, 20, 20},
  //FSI_OSD3
  { FONT_ARIAL, C_OSD_FONT, 0, 22, 22},
  //FSI_OSD4
  { FONT_ARIAL, C_OSD_FONT, 0, 24, 24},
  //FSI_OSD5
  { FONT_ARIAL, C_OSD_FONT, 0, 26, 26},
  //FSI_OSD6
  { FONT_ARIAL, C_OSD_FONT, 0, 32, 32},
  //FSI_OSD7
  { FONT_ARIAL, C_OSD_FONT, 0, 34, 34},
  //FSI_OSD8
  { FONT_ARIAL, C_OSD_FONT, 0, 28, 28},
  //FSI_OSD9
  { FONT_ARIAL, C_OSD_FONT, 0, 36, 36},
  //FSI_OSD10
  { FONT_ARIAL, C_OSD_FONT, 0, 48, 48},
  //FSI_OSD11
  { FONT_ARIAL, C_OSD_FONT, 0, 8, 8},
  //FSI_OSD12
  { FONT_ARIAL, C_OSD_FONT, 0, 12, 12},
  //FSI_OSD13
  { FONT_ARIAL, C_OSD_FONT, 0, 16, 16},
  //FSI_ROLL_OSD1
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 18, 18},
  //FSI_ROLL_OSD2
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 20, 20},
  //FSI_ROLL_OSD3
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 22, 22},
  //FSI_ROLL_OSD4
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 24, 24},
  //FSI_ROLL_OSD5
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 26, 26},
  //FSI_ROLL_OSD6
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 32, 32},
  //FSI_ROLL_OSD7
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 34, 34},
  //FSI_ROLL_OSD8
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 28, 28},
  //FSI_ROLL_OSD9
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 36, 36},
  //FSI_ROLL_OSD10
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 48, 48},
  //FSI_ROLL_OSD11
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 8, 8},
  //FSI_ROLL_OSD12
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 12, 12},
  //FSI_ROLL_OSD13
  { FONT_ARIAL, C_ROLL_OSD_FONT, 0, 16, 16},
  //FSI_FINGER1
  { FONT_ARIAL, C_FINGER_FONT, 0, 18, 18},
  //FSI_FINGER2
  { FONT_ARIAL, C_FINGER_FONT, 0, 20, 20},
  //FSI_FINGER3
  { FONT_ARIAL, C_FINGER_FONT, 0, 22, 22},   
  //FSI_FINGER4
  { FONT_ARIAL, C_FINGER_FONT, 0, 24, 24},  
  //FSI_FINGER5
  { FONT_ARIAL, C_FINGER_FONT, 0, 26, 26},  
  //FSI_FINGER6
  { FONT_ARIAL, C_FINGER_FONT, 0, 32, 32},  
  //FSI_FINGER7
  { FONT_ARIAL, C_FINGER_FONT, 0, 34, 34},  
  //FSI_FINGER8
  { FONT_ARIAL, C_FINGER_FONT, 0, 36, 36},
  //FSI_FINGER9
  { FONT_ARIAL, C_FINGER_FONT, 0, 38, 38},
  //FSI_FINGER10
  { FONT_ARIAL, C_FINGER_FONT, 0, 40, 40},
  //FSI_FINGER11
  { FONT_ARIAL, C_FINGER_FONT, 0, 42, 42},
  //FSI_FINGER12
  { FONT_ARIAL, C_FINGER_FONT, 0, 44, 44},
  //FSI_FINGER13
  { FONT_ARIAL, C_FINGER_FONT, 0, 46, 46},
  //FSI_FINGER FOR AISAT
  { FONT_ARIAL, C_FINGER_FONT, 0, 24, 24},
  //FSI_ROLL_OSD
  { FONT_ARIAL, C_WHITE, 0, 42, 42},
#ifdef ENABLE_NETWORK
  //FSI_LARGE WHITE
  { FONT_ARIAL, C_WHITE, 0, 30, 30},
   //FSI_LARGE WHITE NET
  { FONT_ARIAL, C_WHITE, 0, 35, 35, VFONT_BOLD},
  //FSI_FONT_GRAY
  { FONT_ARIAL, C_FONT_GRAY , 0, 0, 18, 18},
  //FSI_WHITE16
  { FONT_ARIAL, C_WHITE, 0, 16, 16},
  //FSI_WHITE20
  { FONT_ARIAL, C_WHITE, 0, 20, 20},
  //FSI_WHITE22
  { FONT_ARIAL, C_WHITE, 0, 22, 22},
  //FSI_WHITE28
  { FONT_ARIAL, C_WHITE, 0, 28, 28},
  //FSI_WHITE30
  { FONT_ARIAL, C_WHITE, 0, 30, 30},
  //FSI_WHITE36
  { FONT_ARIAL, C_WHITE, 0, 36, 36},
  //FSI_YELLOW_26
  { FONT_ARIAL, C_YELLOW, 0, 26, 26},
  //FSI_BLACK_16
  { FONT_ARIAL, C_BLACK, 0, 16, 16},
  //FSI_BLACK_20
  { FONT_ARIAL, C_BLACK, 0, 20, 20},
  //FSI_VERMILION
  { FONT_ARIAL, C_RED, 0, 24, 24},
  //FSI_HUGE
  { FONT_ARIAL, C_YELLOW, 0, 72, 72},
  //FSI_BLUE_NEWS
  { FONT_ARIAL,  C_BLUE, 0, 20, 20},  
  //FSI_WHITE_S
  { FONT_ARIAL,  C_WHITE, 0, 15, 15},
#endif
};

rsc_config_t g_rsc_config =
{
  512,              // common data buf size
#ifdef ENABLE_NETWORK
  220 * 250 * 4,    //max bitmap size,every pixel cost 2 Byte
#else
  120 * 120 * 4,    //max bitmap size,every pixel cost 2 Byte
#endif
  0,                //max language size,every char cast 2 Bytes
  256 * 4,          //palette size,every color cost 2 Bytes
  0,                //must bigger than latin font size
  0,                //script buffer size
  0,                //offset for block
  0,                //flash base addr
  RSTYLE_CNT,       //rstyle count.
  c_tab,            //rstyle table.
  FSTYLE_CNT,       //fstyle count.
  f_tab,            //fstyle table.
};

