/********************************************************************************************/
/* Copyright (c) 2014 Montage Technology Group Limited and its affiliated companies         */
/* Montage Proprietary and Confidential                                                     */
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/********************************************************************************************/
/****************************************************************************

 ****************************************************************************/
#ifndef __UI_MANUAL_SEARCH_H__
#define __UI_MANUAL_SEARCH_H__

/* coordinate */
#define MANUAL_SEARCH_CONT_X			((SCREEN_WIDTH-MANUAL_SEARCH_CONT_W)/2)
#define MANUAL_SEARCH_CONT_W        COMM_BG_W
#define MANUAL_SEARCH_CONT_H			420

#define MANUAL_SEARCH_V_GAP               15

//specify tp frm
#define MANUAL_SEARCH_SPECIFY_TP_FRM_X     100
#define MANUAL_SEARCH_SPECIFY_TP_FRM_Y     COMM_ITEM_OY_IN_ROOT//120
#define MANUAL_SEARCH_SPECIFY_TP_FRM_W     (MANUAL_SEARCH_CONT_W - 2 * MANUAL_SEARCH_SPECIFY_TP_FRM_X)
#define MANUAL_SEARCH_SPECIFY_TP_FRM_H      (MANUAL_SEARCH_ITEM_CNT * (MANUAL_SEARCH_ITEM_H + MANUAL_SEARCH_ITEM_V_GAP) + 20)


//searching info frm
#define MANUAL_SEARCH_SIG_INFO_FRM_X        70
#define MANUAL_SEARCH_SIG_INFO_FRM_Y        (MANUAL_SEARCH_SPECIFY_TP_FRM_Y + MANUAL_SEARCH_SPECIFY_TP_FRM_H\
                                                                              + MANUAL_SEARCH_V_GAP)
#define MANUAL_SEARCH_SIG_INFO_FRM_W        (COMM_BG_W - MANUAL_SEARCH_SIG_INFO_FRM_X)
#define MANUAL_SEARCH_SIG_INFO_FRM_H        140

//signal strength name
#define MANUAL_SEARCH_SIG_STRENGTH_NAME_X       70
#define MANUAL_SEARCH_SIG_STRENGTH_NAME_Y       20
#define MANUAL_SEARCH_SIG_STRENGTH_NAME_W       150
#define MANUAL_SEARCH_SIG_STRENGTH_NAME_H       30

//signal strength percent
#define MANUAL_SEARCH_SIG_STRENGTH_PERCENT_X    (MANUAL_SEARCH_SIG_STRENGTH_NAME_X + MANUAL_SEARCH_SIG_STRENGTH_NAME_W)
#define MANUAL_SEARCH_SIG_STRENGTH_PERCENT_Y    MANUAL_SEARCH_SIG_STRENGTH_NAME_Y
#define MANUAL_SEARCH_SIG_STRENGTH_PERCENT_W    90
#define MANUAL_SEARCH_SIG_STRENGTH_PERCENT_H    30

//signal strength pbar
#define MANUAL_SEARCH_SIG_STRENGTH_PBAR_X       (MANUAL_SEARCH_SIG_STRENGTH_PERCENT_X + MANUAL_SEARCH_SIG_STRENGTH_PERCENT_W)
#define MANUAL_SEARCH_SIG_STRENGTH_PBAR_Y       (MANUAL_SEARCH_SIG_STRENGTH_PERCENT_Y + (MANUAL_SEARCH_SIG_STRENGTH_NAME_H - MANUAL_SEARCH_SIG_STRENGTH_PERCENT_H)/2)
#define MANUAL_SEARCH_SIG_STRENGTH_PBAR_W       (COMM_BG_W - 2 * (MANUAL_SEARCH_SIG_INFO_FRM_X + MANUAL_SEARCH_SIG_STRENGTH_NAME_X )- MANUAL_SEARCH_SIG_STRENGTH_NAME_W - MANUAL_SEARCH_SIG_STRENGTH_PERCENT_W)
#define MANUAL_SEARCH_SIG_STRENGTH_PBAR_H       16

//signal BER name
#define MANUAL_SEARCH_SIG_BER_NAME_X       MANUAL_SEARCH_SIG_STRENGTH_NAME_X
#define MANUAL_SEARCH_SIG_BER_NAME_Y       (MANUAL_SEARCH_SIG_STRENGTH_NAME_Y + MANUAL_SEARCH_SIG_STRENGTH_NAME_H + MANUAL_SEARCH_V_GAP)
#define MANUAL_SEARCH_SIG_BER_NAME_W       MANUAL_SEARCH_SIG_STRENGTH_NAME_W
#define MANUAL_SEARCH_SIG_BER_NAME_H       MANUAL_SEARCH_SIG_STRENGTH_NAME_H

//signal BER percent
#define MANUAL_SEARCH_SIG_BER_PERCENT_X    MANUAL_SEARCH_SIG_STRENGTH_PERCENT_X
#define MANUAL_SEARCH_SIG_BER_PERCENT_Y    MANUAL_SEARCH_SIG_BER_NAME_Y
#define MANUAL_SEARCH_SIG_BER_PERCENT_W    MANUAL_SEARCH_SIG_STRENGTH_PERCENT_W
#define MANUAL_SEARCH_SIG_BER_PERCENT_H    MANUAL_SEARCH_SIG_STRENGTH_PERCENT_H

//signal BER pbar
#define MANUAL_SEARCH_SIG_BER_PBAR_X       MANUAL_SEARCH_SIG_STRENGTH_PBAR_X
#define MANUAL_SEARCH_SIG_BER_PBAR_Y       (MANUAL_SEARCH_SIG_BER_NAME_Y + (MANUAL_SEARCH_SIG_BER_NAME_H - MANUAL_SEARCH_SIG_BER_PBAR_H)/2)
#define MANUAL_SEARCH_SIG_BER_PBAR_W       MANUAL_SEARCH_SIG_STRENGTH_PBAR_W
#define MANUAL_SEARCH_SIG_BER_PBAR_H       MANUAL_SEARCH_SIG_STRENGTH_PBAR_H

//signal SNR name
#define MANUAL_SEARCH_SIG_SNR_NAME_X       MANUAL_SEARCH_SIG_STRENGTH_NAME_X
#define MANUAL_SEARCH_SIG_SNR_NAME_Y       (MANUAL_SEARCH_SIG_BER_NAME_Y + MANUAL_SEARCH_SIG_BER_NAME_H + MANUAL_SEARCH_V_GAP)
#define MANUAL_SEARCH_SIG_SNR_NAME_W       MANUAL_SEARCH_SIG_STRENGTH_NAME_W
#define MANUAL_SEARCH_SIG_SNR_NAME_H       MANUAL_SEARCH_SIG_STRENGTH_NAME_H

//signal SNR percent
#define MANUAL_SEARCH_SIG_SNR_PERCENT_X    MANUAL_SEARCH_SIG_STRENGTH_PERCENT_X
#define MANUAL_SEARCH_SIG_SNR_PERCENT_Y    MANUAL_SEARCH_SIG_SNR_NAME_Y
#define MANUAL_SEARCH_SIG_SNR_PERCENT_W    MANUAL_SEARCH_SIG_STRENGTH_PERCENT_W
#define MANUAL_SEARCH_SIG_SNR_PERCENT_H    MANUAL_SEARCH_SIG_STRENGTH_PERCENT_H

//signal SNR pbar
#define MANUAL_SEARCH_SIG_SNR_PBAR_X       MANUAL_SEARCH_SIG_STRENGTH_PBAR_X
#define MANUAL_SEARCH_SIG_SNR_PBAR_Y       (MANUAL_SEARCH_SIG_SNR_NAME_Y + (MANUAL_SEARCH_SIG_SNR_NAME_H - MANUAL_SEARCH_SIG_SNR_PBAR_H)/2)
#define MANUAL_SEARCH_SIG_SNR_PBAR_W       MANUAL_SEARCH_SIG_STRENGTH_PBAR_W
#define MANUAL_SEARCH_SIG_SNR_PBAR_H       MANUAL_SEARCH_SIG_STRENGTH_PBAR_H

#define MANUAL_SEARCH_ITEM_CNT		5
#define MANUAL_SEARCH_ITEM_X			20 //COMM_ITEM_OX_IN_ROOT
#define MANUAL_SEARCH_ITEM_Y			10 //COMM_ITEM_OY_IN_ROOT
#define MANUAL_SEARCH_ITEM_LW		COMM_ITEM_LW
#define MANUAL_SEARCH_ITEM_RW		(COMM_ITEM_MAX_WIDTH - MANUAL_SEARCH_ITEM_LW)
#define MANUAL_SEARCH_ITEM_H			COMM_ITEM_H
#define MANUAL_SEARCH_ITEM_V_GAP		0//4 //16

#define RSI_MANUAL_SEARCH_PBAR_BG           RSI_PROGRESS_BAR_BG
#define RSI_MANUAL_SEARCH_PBAR_MID          RSI_PROGRESS_BAR_MID_ORANGE

#define MANUAL_SEARCH_MAX_CNT    10

/* rect style */
#define RSI_MANUAL_SEARCH_FRM		RSI_COMMON_RECT1
/* font style */

/* others */

RET_CODE open_manual_search (u32 para1, u32 para2);
BOOL manual_search_is_finish(void);
RET_CODE preopen_manual_search(u32 para1, u32 para2);
#endif

