/********************************************************************************************/
/* Copyright (c) 2014 Montage Technology Group Limited and its affiliated companies         */
/* Montage Proprietary and Confidential                                                     */
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/********************************************************************************************/
/****************************************************************************

 ****************************************************************************/
#ifndef __UI_RANGE_SEARCH_H__
#define __UI_RANGE_SEARCH_H__

/* coordinate */
#define RANGE_SEARCH_CONT_X			((COMM_BG_W-RANGE_SEARCH_CONT_W)/2)
#define RANGE_SEARCH_CONT_W     COMM_BG_W
#define RANGE_SEARCH_CONT_H			420

#define RANGE_SEARCH_V_GAP               15

//specify tp frm
#define RANGE_SEARCH_SPECIFY_TP_FRM_X     100
#define RANGE_SEARCH_SPECIFY_TP_FRM_Y     COMM_ITEM_OY_IN_ROOT//120
#define RANGE_SEARCH_SPECIFY_TP_FRM_W     (COMM_BG_W - 2 * RANGE_SEARCH_SPECIFY_TP_FRM_X)
#define RANGE_SEARCH_SPECIFY_TP_FRM_H     (RANGE_SEARCH_ITEM_CNT * (RANGE_SEARCH_ITEM_H + RANGE_SEARCH_ITEM_V_GAP) + 20)

//searching info frm
#define RANGE_SEARCH_SIG_INFO_FRM_X        70
#define RANGE_SEARCH_SIG_INFO_FRM_Y        (RANGE_SEARCH_SPECIFY_TP_FRM_Y + RANGE_SEARCH_SPECIFY_TP_FRM_H\
                                                                            + RANGE_SEARCH_V_GAP)
#define RANGE_SEARCH_SIG_INFO_FRM_W        (COMM_BG_W - RANGE_SEARCH_SIG_INFO_FRM_X)
#define RANGE_SEARCH_SIG_INFO_FRM_H        140

//signal strength name
#define RANGE_SEARCH_SIG_STRENGTH_NAME_X       70
#define RANGE_SEARCH_SIG_STRENGTH_NAME_Y       20
#define RANGE_SEARCH_SIG_STRENGTH_NAME_W       150
#define RANGE_SEARCH_SIG_STRENGTH_NAME_H       30

//signal strength percent
#define RANGE_SEARCH_SIG_STRENGTH_PERCENT_X    (RANGE_SEARCH_SIG_STRENGTH_NAME_X + RANGE_SEARCH_SIG_STRENGTH_NAME_W)
#define RANGE_SEARCH_SIG_STRENGTH_PERCENT_Y    RANGE_SEARCH_SIG_STRENGTH_NAME_Y
#define RANGE_SEARCH_SIG_STRENGTH_PERCENT_W    90
#define RANGE_SEARCH_SIG_STRENGTH_PERCENT_H    30

//signal strength pbar
#define RANGE_SEARCH_SIG_STRENGTH_PBAR_X       (RANGE_SEARCH_SIG_STRENGTH_PERCENT_X + RANGE_SEARCH_SIG_STRENGTH_PERCENT_W)
#define RANGE_SEARCH_SIG_STRENGTH_PBAR_Y       (RANGE_SEARCH_SIG_STRENGTH_PERCENT_Y + (RANGE_SEARCH_SIG_STRENGTH_NAME_H - RANGE_SEARCH_SIG_STRENGTH_PERCENT_H)/2)
#define RANGE_SEARCH_SIG_STRENGTH_PBAR_W       (COMM_BG_W - 2 * (RANGE_SEARCH_SIG_INFO_FRM_X + RANGE_SEARCH_SIG_STRENGTH_NAME_X) - RANGE_SEARCH_SIG_STRENGTH_NAME_W - RANGE_SEARCH_SIG_STRENGTH_PERCENT_W)
#define RANGE_SEARCH_SIG_STRENGTH_PBAR_H       16

//signal BER name
#define RANGE_SEARCH_SIG_BER_NAME_X       RANGE_SEARCH_SIG_STRENGTH_NAME_X
#define RANGE_SEARCH_SIG_BER_NAME_Y       (RANGE_SEARCH_SIG_STRENGTH_NAME_Y + RANGE_SEARCH_SIG_STRENGTH_NAME_H + RANGE_SEARCH_V_GAP)
#define RANGE_SEARCH_SIG_BER_NAME_W       RANGE_SEARCH_SIG_STRENGTH_NAME_W
#define RANGE_SEARCH_SIG_BER_NAME_H       RANGE_SEARCH_SIG_STRENGTH_NAME_H

//signal BER percent
#define RANGE_SEARCH_SIG_BER_PERCENT_X    RANGE_SEARCH_SIG_STRENGTH_PERCENT_X
#define RANGE_SEARCH_SIG_BER_PERCENT_Y    RANGE_SEARCH_SIG_BER_NAME_Y
#define RANGE_SEARCH_SIG_BER_PERCENT_W    RANGE_SEARCH_SIG_STRENGTH_PERCENT_W
#define RANGE_SEARCH_SIG_BER_PERCENT_H    RANGE_SEARCH_SIG_STRENGTH_PERCENT_H

//signal BER pbar
#define RANGE_SEARCH_SIG_BER_PBAR_X       RANGE_SEARCH_SIG_STRENGTH_PBAR_X
#define RANGE_SEARCH_SIG_BER_PBAR_Y       (RANGE_SEARCH_SIG_BER_NAME_Y + (RANGE_SEARCH_SIG_BER_NAME_H - RANGE_SEARCH_SIG_BER_PBAR_H)/2)
#define RANGE_SEARCH_SIG_BER_PBAR_W       RANGE_SEARCH_SIG_STRENGTH_PBAR_W
#define RANGE_SEARCH_SIG_BER_PBAR_H       RANGE_SEARCH_SIG_STRENGTH_PBAR_H

//signal SNR name
#define RANGE_SEARCH_SIG_SNR_NAME_X       RANGE_SEARCH_SIG_STRENGTH_NAME_X
#define RANGE_SEARCH_SIG_SNR_NAME_Y       (RANGE_SEARCH_SIG_BER_NAME_Y + RANGE_SEARCH_SIG_BER_NAME_H + RANGE_SEARCH_V_GAP)
#define RANGE_SEARCH_SIG_SNR_NAME_W       RANGE_SEARCH_SIG_STRENGTH_NAME_W
#define RANGE_SEARCH_SIG_SNR_NAME_H       RANGE_SEARCH_SIG_STRENGTH_NAME_H

//signal SNR percent
#define RANGE_SEARCH_SIG_SNR_PERCENT_X    RANGE_SEARCH_SIG_STRENGTH_PERCENT_X
#define RANGE_SEARCH_SIG_SNR_PERCENT_Y    RANGE_SEARCH_SIG_SNR_NAME_Y
#define RANGE_SEARCH_SIG_SNR_PERCENT_W    RANGE_SEARCH_SIG_STRENGTH_PERCENT_W
#define RANGE_SEARCH_SIG_SNR_PERCENT_H    RANGE_SEARCH_SIG_STRENGTH_PERCENT_H

//signal SNR pbar
#define RANGE_SEARCH_SIG_SNR_PBAR_X       RANGE_SEARCH_SIG_STRENGTH_PBAR_X
#define RANGE_SEARCH_SIG_SNR_PBAR_Y       (RANGE_SEARCH_SIG_SNR_NAME_Y + (RANGE_SEARCH_SIG_SNR_NAME_H - RANGE_SEARCH_SIG_SNR_PBAR_H)/2)
#define RANGE_SEARCH_SIG_SNR_PBAR_W       RANGE_SEARCH_SIG_STRENGTH_PBAR_W
#define RANGE_SEARCH_SIG_SNR_PBAR_H       RANGE_SEARCH_SIG_STRENGTH_PBAR_H

#define RANGE_SEARCH_ITEM_CNT		5
#define RANGE_SEARCH_ITEM_X			20//COMM_ITEM_OX_IN_ROOT
#define RANGE_SEARCH_ITEM_Y			10//COMM_ITEM_OY_IN_ROOT
#define RANGE_SEARCH_ITEM_LW		COMM_ITEM_LW
#define RANGE_SEARCH_ITEM_RW		(COMM_ITEM_MAX_WIDTH - RANGE_SEARCH_ITEM_LW)
#define RANGE_SEARCH_ITEM_H			COMM_ITEM_H
#define RANGE_SEARCH_ITEM_V_GAP		0//16

#define RSI_RANGE_SEARCH_PBAR_BG           RSI_PROGRESS_BAR_BG
#define RSI_RANGE_SEARCH_PBAR_MID          RSI_PROGRESS_BAR_MID_ORANGE

#define RANGE_SEARCH_MAX_CNT    10

/* rect style */
#define RSI_RANGE_SEARCH_FRM		RSI_COMMON_RECT1
/* font style */

/* others */

RET_CODE open_range_search (u32 para1, u32 para2);
RET_CODE preopen_range_search(u32 para1, u32 para2);
#endif

