/********************************************************************************************/
/* Copyright (c) 2014 Montage Technology Group Limited and its affiliated companies         */
/* Montage Proprietary and Confidential                                                     */
/* Montage Technology (Shanghai) Co., Ltd.                                                  */
/********************************************************************************************/
/****************************************************************************

 ****************************************************************************/
#ifndef _UI_REC_MANAGER_H_
#define _UI_REC_MANAGER_H_

#include "ui_common.h"

/*coordinates*/

//preview
#define REC_MANAGER_PREV_X  PREV_COMMON_X
#define REC_MANAGER_PREV_Y  (PREV_COMMON_Y + 10)
#define REC_MANAGER_PREV_W  PREV_COMMON_W
#define REC_MANAGER_PREV_H  PREV_COMMON_H

#define REC_MANAGER_LIST_TITLE_X (REC_MANAGER_PREV_X + REC_MANAGER_PREV_W + 20)
#define REC_MANAGER_LIST_TITLE_Y REC_MANAGER_PREV_Y
#define REC_MANAGER_LIST_TITLE_W (COMM_BG_W - REC_MANAGER_LIST_TITLE_X - WIN_LR_SPACE)
#define REC_MANAGER_LIST_TITLE_H COMM_ITEM_H

#define REC_MANAGER_TXT_OFFSETX 30
#define REC_MANAGER_TXT_OFFSETY 0

//DETAIL
#define REC_MANAGER_DETAIL_X  REC_MANAGER_PREV_X
#ifdef RECORD_MANAGER_PREVIEW
#define REC_MANAGER_DETAIL_Y  (REC_MANAGER_PREV_Y + REC_MANAGER_PREV_H + 20)
#else
#define REC_MANAGER_DETAIL_Y  REC_MANAGER_LISTY
#endif

#define REC_MANAGER_DETAIL_W  REC_MANAGER_PREV_W
#ifdef RECORD_MANAGER_PREVIEW
#define REC_MANAGER_DETAIL_H  150//150
#else
#define REC_MANAGER_DETAIL_H  REC_MANAGER_LISTH
#endif

//NAME
#define REC_MANAGER_DETAIL_PGX  0
#define REC_MANAGER_DETAIL_PGY  10
#define REC_MANAGER_DETAIL_PGW  REC_MANAGER_DETAIL_W//240
#define REC_MANAGER_DETAIL_PGH  36

//total time
#define REC_MANAGER_DETAIL_TIMETOTALX  0
#define REC_MANAGER_DETAIL_TIMETOTALY  (REC_MANAGER_DETAIL_PGY + REC_MANAGER_DETAIL_PGH + 10)
#define REC_MANAGER_DETAIL_TIMETOTALW  REC_MANAGER_DETAIL_W

//file size
#define REC_MANAGER_DETAIL_FILESIZEX  0
#ifdef RECORD_MANAGER_PREVIEW
#define REC_MANAGER_DETAIL_FILESIZEY  (REC_MANAGER_DETAIL_H -  REC_MANAGER_DETAIL_PGH - 10)
#else
#define REC_MANAGER_DETAIL_FILESIZEY  (REC_MANAGER_DETAIL_TIMETOTALY + REC_MANAGER_DETAIL_PGH + 10)
#endif
#define REC_MANAGER_DETAIL_FILESIZEW  REC_MANAGER_DETAIL_W

#define REC_MANAGER_DETAIL_VGAP 4

#ifndef RECORD_MANAGER_PREVIEW
#define REC_MANAGER_PARENTAL_LOCKX  0
#define REC_MANAGER_PARENTAL_LOCKY  (REC_MANAGER_DETAIL_FILESIZEY + REC_MANAGER_DETAIL_PGH)
#define REC_MANAGER_PARENTAL_LOCKW  REC_MANAGER_DETAIL_W
#define REC_MANAGER_PARENTAL_LOCKH  (REC_MANAGER_DETAIL_H - REC_MANAGER_DETAIL_FILESIZEY - REC_MANAGER_DETAIL_PGH)
#endif

#define REC_MANAGER_TIME_X  700
#define REC_MANAGER_TIME_Y  30
#define REC_MANAGER_TIME_W  170
#define REC_MANAGER_TIME_H  36

//list
#define REC_MANAGER_LISTX REC_MANAGER_LIST_TITLE_X
#define REC_MANAGER_LISTY (REC_MANAGER_LIST_TITLE_Y + REC_MANAGER_LIST_TITLE_H + 10)
#define REC_MANAGER_LISTW (REC_MANAGER_LIST_TITLE_W - 10)
#define REC_MANAGER_LISTH 340//420

#define REC_MANAGER_LIST_MIDL  8
#define REC_MANAGER_LIST_MIDT  8
#define REC_MANAGER_LIST_MIDW  (REC_MANAGER_LISTW - 2 * REC_MANAGER_LIST_MIDL)
#define REC_MANAGER_LIST_MIDH  (REC_MANAGER_LISTH - 2 * REC_MANAGER_LIST_MIDT)

#define REC_MANAGER_LCONT_LIST_VGAP 4

#define REC_MANAGER_LIST_SBARX  (REC_MANAGER_LISTX + REC_MANAGER_LISTW +4)
#define REC_MANAGER_LIST_SBARY  (REC_MANAGER_LISTY)
#define REC_MANAGER_LIST_SBARW  6
#define REC_MANAGER_LIST_SBARH  REC_MANAGER_LISTH

#define REC_MANAGER_LIST_SBAR_MIDL  0
#define REC_MANAGER_LIST_SBAR_MIDT  12
#define REC_MANAGER_LIST_SBAR_MIDR  6
#define REC_MANAGER_LIST_SBAR_MIDB  (REC_MANAGER_LIST_SBARH - REC_MANAGER_LIST_SBAR_MIDT)

//password dialogue
#define REC_MANAGER_PWD_DLG_FOR_CHK_X      ((SCREEN_WIDTH-PWDLG_W)/2)
#define REC_MANAGER_PWD_DLG_FOR_CHK_Y      ((SCREEN_HEIGHT-PWDLG_H)/2)


/*rstyle*/
#define RSI_REC_MANAGER_PREV  RSI_TV
#define RSI_REC_MANAGER_DETAIL  RSI_COMMON_RECT1
#define RSI_REC_MANAGER_SBAR RSI_SCROLL_BAR_BG
#define RSI_REC_MANAGER_SBAR_MID RSI_SCROLL_BAR_MID
#define RSI_REC_MANAGER_LCONT_LIST  RSI_COMMON_RECT1

/*others*/
#define REC_MANAGER_LIST_PAGE 8//10//5
#define REC_MANAGER_LIST_FIELD 3//6
enum rec_manager_list_field_item
{
  REC_MANAGER_LIST_NO = 0,
  REC_MANAGER_LIST_LOCK,
  REC_MANAGER_LIST_NAME
};

#define REC_MANAGER_LCONT_MBOX_TOL  4
#define REC_MANAGER_LCONT_MBOX_COL  4
#define REC_MANAGER_LCONT_MBOX_ROW  1
#define REC_MANAGER_LCONT_MBOX_HGAP  0
#define REC_MANAGER_LCONT_MBOX_VGAP  0

#define REC_MANAGER_INFO_MBOX_TOL  2
#define REC_MANAGER_INFO_MBOX_COL  2
#define REC_MANAGER_INFO_MBOX_ROW  1
#define REC_MANAGER_INFO_MBOX_HGAP  4
#define REC_MANAGER_INFO_MBOX_VGAP  0

#define REC_MANAGER_TIME_PBAR_MIN 0
#define REC_MANAGER_TIME_PBAR_MAX 66

#define REC_MANAGER_TIME_TOT_HOURS 2

/*fstyle*/
#define FSI_REC_MANAGER_LCONT_MBOX FSI_WHITE
#define FSI_REC_MANAGER_INFO_MBOX FSI_WHITE

/*file name max length*/
#define REC_FILE_NAME_LEN   33
#define TS_FILE_MAX_CNT 20

void ui_rec_manager_destroy(void);

RET_CODE open_record_manager(u32 para1, u32 para2);
void rec_manager_init_param(void);

#endif
